/* =========================================================
   NionVN — Dữ liệu mẫu (có thể mở rộng thêm ở cuối file)
   Cấu trúc dữ liệu được thiết kế đơn giản để bạn tự thêm từ mới.
   ========================================================= */

const VOCAB = [
// ===== Từ nền tảng (đại từ, từ hỏi, động từ/tính từ cực kỳ thông dụng) =====
// Bổ sung riêng để tính năng Dịch và các câu ví dụ cơ bản nhận diện được.
{kanji:"私",hira:"わたし",kata:"",romaji:"watashi",pos:"Đại từ",level:"N5",topic:"Đại từ",
 vi:["tôi"],en:["I, me"],jp:"自分を指す言葉。",examples:[{jp:"私は学生です。",romaji:"Watashi wa gakusei desu.",vi:"Tôi là học sinh."}],synonyms:["僕","私"],compounds:[]},
{kanji:"僕",hira:"ぼく",kata:"",romaji:"boku",pos:"Đại từ",level:"N5",topic:"Đại từ",
 vi:["tôi (nam giới dùng)"],en:["I (male)"],jp:"男性が使う「私」。",examples:[{jp:"僕は行きます。",romaji:"Boku wa ikimasu.",vi:"Tôi sẽ đi."}],synonyms:["私"],compounds:[]},
{kanji:"あなた",hira:"あなた",kata:"",romaji:"anata",pos:"Đại từ",level:"N5",topic:"Đại từ",
 vi:["bạn","anh/chị"],en:["you"],jp:"相手を指す言葉。",examples:[{jp:"あなたは誰ですか。",romaji:"Anata wa dare desu ka.",vi:"Bạn là ai?"}],synonyms:[],compounds:[]},
{kanji:"彼",hira:"かれ",kata:"",romaji:"kare",pos:"Đại từ",level:"N5",topic:"Đại từ",
 vi:["anh ấy"],en:["he"],jp:"男性を指す言葉。",examples:[{jp:"彼は先生です。",romaji:"Kare wa sensei desu.",vi:"Anh ấy là giáo viên."}],synonyms:[],compounds:[]},
{kanji:"彼女",hira:"かのじょ",kata:"",romaji:"kanojo",pos:"Đại từ",level:"N5",topic:"Đại từ",
 vi:["cô ấy","bạn gái"],en:["she, girlfriend"],jp:"女性を指す言葉。",examples:[{jp:"彼女は医者です。",romaji:"Kanojo wa isha desu.",vi:"Cô ấy là bác sĩ."}],synonyms:[],compounds:[]},
{kanji:"これ",hira:"これ",kata:"",romaji:"kore",pos:"Đại từ chỉ định",level:"N5",topic:"Đại từ",
 vi:["cái này"],en:["this"],jp:"近くのものを指す言葉。",examples:[{jp:"これは本です。",romaji:"Kore wa hon desu.",vi:"Đây là quyển sách."}],synonyms:[],compounds:[]},
{kanji:"それ",hira:"それ",kata:"",romaji:"sore",pos:"Đại từ chỉ định",level:"N5",topic:"Đại từ",
 vi:["cái đó"],en:["that"],jp:"少し離れたものを指す言葉。",examples:[{jp:"それは何ですか。",romaji:"Sore wa nan desu ka.",vi:"Cái đó là gì?"}],synonyms:[],compounds:[]},
{kanji:"あれ",hira:"あれ",kata:"",romaji:"are",pos:"Đại từ chỉ định",level:"N5",topic:"Đại từ",
 vi:["cái kia"],en:["that (over there)"],jp:"遠くのものを指す言葉。",examples:[{jp:"あれは山です。",romaji:"Are wa yama desu.",vi:"Kia là núi."}],synonyms:[],compounds:[]},
{kanji:"ここ",hira:"ここ",kata:"",romaji:"koko",pos:"Đại từ chỉ định",level:"N5",topic:"Đại từ",
 vi:["ở đây"],en:["here"],jp:"近くの場所。",examples:[{jp:"ここに座ってください。",romaji:"Koko ni suwatte kudasai.",vi:"Hãy ngồi ở đây."}],synonyms:[],compounds:[]},
{kanji:"そこ",hira:"そこ",kata:"",romaji:"soko",pos:"Đại từ chỉ định",level:"N5",topic:"Đại từ",
 vi:["ở đó"],en:["there"],jp:"少し離れた場所。",examples:[{jp:"そこに置いてください。",romaji:"Soko ni oite kudasai.",vi:"Hãy để nó ở đó."}],synonyms:[],compounds:[]},
{kanji:"どこ",hira:"どこ",kata:"",romaji:"doko",pos:"Đại từ nghi vấn",level:"N5",topic:"Từ hỏi",
 vi:["ở đâu"],en:["where"],jp:"場所を尋ねる言葉。",examples:[{jp:"駅はどこですか。",romaji:"Eki wa doko desu ka.",vi:"Nhà ga ở đâu?"}],synonyms:[],compounds:[]},
{kanji:"何",hira:"なに",kata:"",romaji:"nani",pos:"Đại từ nghi vấn",level:"N5",topic:"Từ hỏi",
 vi:["cái gì","gì"],en:["what"],jp:"物事を尋ねる言葉。",examples:[{jp:"これは何ですか。",romaji:"Kore wa nan desu ka.",vi:"Đây là cái gì?"}],synonyms:[],compounds:[]},
{kanji:"誰",hira:"だれ",kata:"",romaji:"dare",pos:"Đại từ nghi vấn",level:"N5",topic:"Từ hỏi",
 vi:["ai"],en:["who"],jp:"人を尋ねる言葉。",examples:[{jp:"あの人は誰ですか。",romaji:"Ano hito wa dare desu ka.",vi:"Người kia là ai?"}],synonyms:[],compounds:[]},
{kanji:"いつ",hira:"いつ",kata:"",romaji:"itsu",pos:"Trạng từ nghi vấn",level:"N5",topic:"Từ hỏi",
 vi:["khi nào"],en:["when"],jp:"時を尋ねる言葉。",examples:[{jp:"いつ日本へ行きますか。",romaji:"Itsu Nihon e ikimasu ka.",vi:"Khi nào bạn đi Nhật?"}],synonyms:[],compounds:[]},
{kanji:"どう",hira:"どう",kata:"",romaji:"dou",pos:"Trạng từ nghi vấn",level:"N5",topic:"Từ hỏi",
 vi:["thế nào","như thế nào"],en:["how"],jp:"様子や方法を尋ねる言葉。",examples:[{jp:"味はどうですか。",romaji:"Aji wa dou desu ka.",vi:"Vị thế nào?"}],synonyms:[],compounds:[]},
{kanji:"どうして",hira:"どうして",kata:"",romaji:"doushite",pos:"Trạng từ nghi vấn",level:"N5",topic:"Từ hỏi",
 vi:["tại sao"],en:["why"],jp:"理由を尋ねる言葉。",examples:[{jp:"どうして遅れたんですか。",romaji:"Doushite okuretan desu ka.",vi:"Tại sao bạn đến trễ?"}],synonyms:["なぜ"],compounds:[]},
{kanji:"いくら",hira:"いくら",kata:"",romaji:"ikura",pos:"Đại từ nghi vấn",level:"N5",topic:"Từ hỏi",
 vi:["bao nhiêu tiền"],en:["how much"],jp:"値段を尋ねる言葉。",examples:[{jp:"これはいくらですか。",romaji:"Kore wa ikura desu ka.",vi:"Cái này bao nhiêu tiền?"}],synonyms:[],compounds:[]},
{kanji:"ある",hira:"ある",kata:"",romaji:"aru",pos:"Động từ nhóm 1",level:"N5",topic:"Động từ cơ bản",
 vi:["có (vật vô tri)"],en:["to exist, to have (things)"],jp:"物が存在すること。",examples:[{jp:"机の上に本があります。",romaji:"Tsukue no ue ni hon ga arimasu.",vi:"Trên bàn có quyển sách."}],synonyms:[],compounds:[]},
{kanji:"いる",hira:"いる",kata:"",romaji:"iru",pos:"Động từ nhóm 2",level:"N5",topic:"Động từ cơ bản",
 vi:["có (người/động vật)"],en:["to exist, to be (living things)"],jp:"人や動物が存在すること。",examples:[{jp:"部屋に猫がいます。",romaji:"Heya ni neko ga imasu.",vi:"Trong phòng có con mèo."}],synonyms:[],compounds:[]},
{kanji:"する",hira:"する",kata:"",romaji:"suru",pos:"Động từ bất quy tắc",level:"N5",topic:"Động từ cơ bản",
 vi:["làm"],en:["to do"],jp:"行動をすること。",examples:[{jp:"宿題をします。",romaji:"Shukudai wo shimasu.",vi:"Tôi làm bài tập."}],synonyms:[],compounds:[]},
{kanji:"なる",hira:"なる",kata:"",romaji:"naru",pos:"Động từ nhóm 1",level:"N5",topic:"Động từ cơ bản",
 vi:["trở thành","trở nên"],en:["to become"],jp:"状態が変わること。",examples:[{jp:"医者になりたいです。",romaji:"Isha ni naritai desu.",vi:"Tôi muốn trở thành bác sĩ."}],synonyms:[],compounds:[]},
{kanji:"行く",hira:"いく",kata:"",romaji:"iku",pos:"Động từ nhóm 1",level:"N5",topic:"Động từ cơ bản",
 vi:["đi"],en:["to go"],jp:"ある場所へ移動すること。",examples:[{jp:"学校へ行きます。",romaji:"Gakkou e ikimasu.",vi:"Tôi đi học."}],synonyms:[],compounds:[]},
{kanji:"来る",hira:"くる",kata:"",romaji:"kuru",pos:"Động từ bất quy tắc",level:"N5",topic:"Động từ cơ bản",
 vi:["đến"],en:["to come"],jp:"こちらへ向かって移動すること。",examples:[{jp:"友達が来ます。",romaji:"Tomodachi ga kimasu.",vi:"Bạn tôi sẽ đến."}],synonyms:[],compounds:[]},
{kanji:"見る",hira:"みる",kata:"",romaji:"miru",pos:"Động từ nhóm 2",level:"N5",topic:"Động từ cơ bản",
 vi:["xem","nhìn"],en:["to see, to watch"],jp:"目で見ること。",examples:[{jp:"テレビを見ます。",romaji:"Terebi wo mimasu.",vi:"Tôi xem tivi."}],synonyms:[],compounds:[]},
{kanji:"言う",hira:"いう",kata:"",romaji:"iu",pos:"Động từ nhóm 1",level:"N5",topic:"Động từ cơ bản",
 vi:["nói"],en:["to say"],jp:"言葉で伝えること。",examples:[{jp:"名前を言ってください。",romaji:"Namae wo itte kudasai.",vi:"Hãy nói tên của bạn."}],synonyms:[],compounds:[]},
{kanji:"分かる",hira:"わかる",kata:"",romaji:"wakaru",pos:"Động từ nhóm 1",level:"N5",topic:"Động từ cơ bản",
 vi:["hiểu"],en:["to understand"],jp:"意味を理解すること。",examples:[{jp:"日本語が分かります。",romaji:"Nihongo ga wakarimasu.",vi:"Tôi hiểu tiếng Nhật."}],synonyms:[],compounds:[]},
{kanji:"好き",hira:"すき",kata:"",romaji:"suki",pos:"Tính từ na",level:"N5",topic:"Cảm xúc",
 vi:["thích"],en:["to like"],jp:"気に入っている様子。",examples:[{jp:"日本料理が好きです。",romaji:"Nihon ryouri ga suki desu.",vi:"Tôi thích món ăn Nhật."}],synonyms:[],compounds:[]},
{kanji:"嫌い",hira:"きらい",kata:"",romaji:"kirai",pos:"Tính từ na",level:"N5",topic:"Cảm xúc",
 vi:["ghét"],en:["to dislike"],jp:"気に入らない様子。",examples:[{jp:"虫が嫌いです。",romaji:"Mushi ga kirai desu.",vi:"Tôi ghét côn trùng."}],synonyms:[],compounds:[]},
{kanji:"今",hira:"いま",kata:"",romaji:"ima",pos:"Danh từ",level:"N5",topic:"Thời gian",
 vi:["bây giờ"],en:["now"],jp:"現在の時。",examples:[{jp:"今何時ですか。",romaji:"Ima nanji desu ka.",vi:"Bây giờ là mấy giờ?"}],synonyms:[],compounds:[]},
{kanji:"今日",hira:"きょう",kata:"",romaji:"kyou",pos:"Danh từ",level:"N5",topic:"Thời gian",
 vi:["hôm nay"],en:["today"],jp:"この日。",examples:[{jp:"今日は忙しいです。",romaji:"Kyou wa isogashii desu.",vi:"Hôm nay tôi bận."}],synonyms:[],compounds:[]},
{kanji:"明日",hira:"あした",kata:"",romaji:"ashita",pos:"Danh từ",level:"N5",topic:"Thời gian",
 vi:["ngày mai"],en:["tomorrow"],jp:"次の日。",examples:[{jp:"明日会いましょう。",romaji:"Ashita aimashou.",vi:"Ngày mai gặp nhau nhé."}],synonyms:[],compounds:[]},
{kanji:"昨日",hira:"きのう",kata:"",romaji:"kinou",pos:"Danh từ",level:"N5",topic:"Thời gian",
 vi:["hôm qua"],en:["yesterday"],jp:"前の日。",examples:[{jp:"昨日は雨でした。",romaji:"Kinou wa ame deshita.",vi:"Hôm qua trời mưa."}],synonyms:[],compounds:[]},
{kanji:"家",hira:"いえ",kata:"",romaji:"ie",pos:"Danh từ",level:"N5",topic:"Địa điểm",
 vi:["nhà"],en:["house, home"],jp:"人が住む建物。",examples:[{jp:"家に帰ります。",romaji:"Ie ni kaerimasu.",vi:"Tôi về nhà."}],synonyms:[],compounds:[]},
{kanji:"会社",hira:"かいしゃ",kata:"",romaji:"kaisha",pos:"Danh từ",level:"N5",topic:"Công việc",
 vi:["công ty"],en:["company"],jp:"仕事をする組織。",examples:[{jp:"会社で働いています。",romaji:"Kaisha de hataraite imasu.",vi:"Tôi làm việc ở công ty."}],synonyms:[],compounds:[]},
{kanji:"車",hira:"くるま",kata:"",romaji:"kuruma",pos:"Danh từ",level:"N5",topic:"Giao thông",
 vi:["xe hơi"],en:["car"],jp:"エンジンで走る乗り物。",examples:[{jp:"車で行きます。",romaji:"Kuruma de ikimasu.",vi:"Tôi đi bằng xe hơi."}],synonyms:[],compounds:[]},
{kanji:"電話",hira:"でんわ",kata:"",romaji:"denwa",pos:"Danh từ / Suru-động từ",level:"N5",topic:"Giao tiếp",
 vi:["điện thoại"],en:["telephone"],jp:"話すための機械。",examples:[{jp:"電話をかけます。",romaji:"Denwa wo kakemasu.",vi:"Tôi gọi điện thoại."}],synonyms:[],compounds:[]},
{kanji:"お金",hira:"おかね",kata:"",romaji:"okane",pos:"Danh từ",level:"N5",topic:"Tiền bạc",
 vi:["tiền"],en:["money"],jp:"物を買うために使うもの。",examples:[{jp:"お金がありません。",romaji:"Okane ga arimasen.",vi:"Tôi không có tiền."}],synonyms:[],compounds:[]},
{kanji:"人",hira:"ひと",kata:"",romaji:"hito",pos:"Danh từ",level:"N5",topic:"Con người",
 vi:["người"],en:["person"],jp:"人間。",examples:[{jp:"あの人は先生です。",romaji:"Ano hito wa sensei desu.",vi:"Người kia là giáo viên."}],synonyms:[],compounds:[]},
{kanji:"名前",hira:"なまえ",kata:"",romaji:"namae",pos:"Danh từ",level:"N5",topic:"Con người",
 vi:["tên"],en:["name"],jp:"人やものの呼び名。",examples:[{jp:"名前は何ですか。",romaji:"Namae wa nan desu ka.",vi:"Tên bạn là gì?"}],synonyms:[],compounds:[]},
{kanji:"学生",hira:"がくせい",kata:"",romaji:"gakusei",pos:"Danh từ",level:"N5",topic:"Trường học",
 vi:["học sinh","sinh viên"],en:["student"],jp:"学校で勉強する人。",examples:[{jp:"私は学生です。",romaji:"Watashi wa gakusei desu.",vi:"Tôi là sinh viên."}],synonyms:[],compounds:[]},
{kanji:"日本語",hira:"にほんご",kata:"",romaji:"nihongo",pos:"Danh từ",level:"N5",topic:"Ngôn ngữ",
 vi:["tiếng Nhật"],en:["Japanese language"],jp:"日本の言葉。",examples:[{jp:"日本語を勉強しています。",romaji:"Nihongo wo benkyou shite imasu.",vi:"Tôi đang học tiếng Nhật."}],synonyms:[],compounds:[]},
{kanji:"会う",hira:"あう",kata:"",romaji:"au",pos:"Động từ nhóm 1",level:"N5",topic:"Động từ cơ bản",
 vi:["gặp"],en:["to meet"],jp:"人と顔を合わせること。",examples:[{jp:"友達に会います。",romaji:"Tomodachi ni aimasu.",vi:"Tôi gặp bạn."}],synonyms:[],compounds:[]},
{kanji:"買う",hira:"かう",kata:"",romaji:"kau",pos:"Động từ nhóm 1",level:"N5",topic:"Động từ cơ bản",
 vi:["mua"],en:["to buy"],jp:"お金を払って手に入れること。",examples:[{jp:"パンを買います。",romaji:"Pan wo kaimasu.",vi:"Tôi mua bánh mì."}],synonyms:[],compounds:[]},
{kanji:"作る",hira:"つくる",kata:"",romaji:"tsukuru",pos:"Động từ nhóm 1",level:"N5",topic:"Động từ cơ bản",
 vi:["làm ra","chế tạo"],en:["to make"],jp:"物を新しく生み出すこと。",examples:[{jp:"料理を作ります。",romaji:"Ryouri wo tsukurimasu.",vi:"Tôi nấu ăn."}],synonyms:[],compounds:[]},
{kanji:"使う",hira:"つかう",kata:"",romaji:"tsukau",pos:"Động từ nhóm 1",level:"N5",topic:"Động từ cơ bản",
 vi:["sử dụng"],en:["to use"],jp:"道具などを役立てること。",examples:[{jp:"パソコンを使います。",romaji:"Pasokon wo tsukaimasu.",vi:"Tôi sử dụng máy tính."}],synonyms:[],compounds:[]},
{kanji:"待つ",hira:"まつ",kata:"",romaji:"matsu",pos:"Động từ nhóm 1",level:"N5",topic:"Động từ cơ bản",
 vi:["chờ, đợi"],en:["to wait"],jp:"時が来るのを待つこと。",examples:[{jp:"友達を待っています。",romaji:"Tomodachi wo matte imasu.",vi:"Tôi đang đợi bạn."}],synonyms:[],compounds:[]},
{kanji:"立つ",hira:"たつ",kata:"",romaji:"tatsu",pos:"Động từ nhóm 1",level:"N5",topic:"Động từ cơ bản",
 vi:["đứng"],en:["to stand"],jp:"体を垂直にして立つこと。",examples:[{jp:"ここに立ってください。",romaji:"Koko ni tatte kudasai.",vi:"Hãy đứng ở đây."}],synonyms:[],compounds:[]},
{kanji:"座る",hira:"すわる",kata:"",romaji:"suwaru",pos:"Động từ nhóm 1",level:"N5",topic:"Động từ cơ bản",
 vi:["ngồi"],en:["to sit"],jp:"腰を下ろすこと。",examples:[{jp:"椅子に座ります。",romaji:"Isu ni suwarimasu.",vi:"Tôi ngồi vào ghế."}],synonyms:[],compounds:[]},
{kanji:"入る",hira:"はいる",kata:"",romaji:"hairu",pos:"Động từ nhóm 1",level:"N5",topic:"Động từ cơ bản",
 vi:["vào"],en:["to enter"],jp:"中に入ること。",examples:[{jp:"部屋に入ります。",romaji:"Heya ni hairimasu.",vi:"Tôi vào phòng."}],synonyms:[],compounds:[]},
{kanji:"出る",hira:"でる",kata:"",romaji:"deru",pos:"Động từ nhóm 2",level:"N5",topic:"Động từ cơ bản",
 vi:["ra, ra ngoài"],en:["to exit, leave"],jp:"外に出ること。",examples:[{jp:"家を出ます。",romaji:"Ie wo demasu.",vi:"Tôi ra khỏi nhà."}],synonyms:[],compounds:[]},
{kanji:"寝る",hira:"ねる",kata:"",romaji:"neru",pos:"Động từ nhóm 2",level:"N5",topic:"Động từ cơ bản",
 vi:["ngủ"],en:["to sleep"],jp:"睡眠をとること。",examples:[{jp:"十時に寝ます。",romaji:"Juuji ni nemasu.",vi:"Tôi ngủ lúc 10 giờ."}],synonyms:[],compounds:[]},
{kanji:"起きる",hira:"おきる",kata:"",romaji:"okiru",pos:"Động từ nhóm 2",level:"N5",topic:"Động từ cơ bản",
 vi:["thức dậy"],en:["to wake up"],jp:"眠りから覚めること。",examples:[{jp:"六時に起きます。",romaji:"Rokuji ni okimasu.",vi:"Tôi thức dậy lúc 6 giờ."}],synonyms:[],compounds:[]},
{kanji:"休む",hira:"やすむ",kata:"",romaji:"yasumu",pos:"Động từ nhóm 1",level:"N5",topic:"Động từ cơ bản",
 vi:["nghỉ ngơi"],en:["to rest"],jp:"体を休めること。",examples:[{jp:"今日は休みます。",romaji:"Kyou wa yasumimasu.",vi:"Hôm nay tôi nghỉ."}],synonyms:[],compounds:[]},
{kanji:"忘れる",hira:"わすれる",kata:"",romaji:"wasureru",pos:"Động từ nhóm 2",level:"N5",topic:"Động từ cơ bản",
 vi:["quên"],en:["to forget"],jp:"覚えていたことを思い出せなくなること。",examples:[{jp:"傘を忘れました。",romaji:"Kasa wo wasuremashita.",vi:"Tôi đã quên cái ô."}],synonyms:[],compounds:[]},


{kanji:"食べる",hira:"たべる",kata:"",romaji:"taberu",pos:"Động từ nhóm 2",level:"N5",topic:"Ăn uống",
 vi:["ăn"],en:["to eat"],jp:"食事をする。物を口に入れて飲み込むこと。",
 examples:[{jp:"朝ごはんを食べます。",romaji:"Asa gohan wo tabemasu.",vi:"Tôi ăn sáng."}],
 synonyms:["召し上がる (kính ngữ)"],compounds:["食べ物 (đồ ăn)","食べ放題 (ăn thỏa thích)"]},

{kanji:"飲む",hira:"のむ",kata:"",romaji:"nomu",pos:"Động từ nhóm 1",level:"N5",topic:"Ăn uống",
 vi:["uống"],en:["to drink"],jp:"液体を口に入れて飲み込むこと。",
 examples:[{jp:"水を飲みます。",romaji:"Mizu wo nomimasu.",vi:"Tôi uống nước."}],
 synonyms:[],compounds:["飲み物 (đồ uống)","飲み会 (buổi nhậu)"]},

{kanji:"学校",hira:"がっこう",kata:"",romaji:"gakkou",pos:"Danh từ",level:"N5",topic:"Trường học",
 vi:["trường học"],en:["school"],jp:"勉強するための施設。",
 examples:[{jp:"毎日学校へ行きます。",romaji:"Mainichi gakkou e ikimasu.",vi:"Tôi đi học mỗi ngày."}],
 synonyms:["スクール"],compounds:["小学校 (tiểu học)","高校 (trung học phổ thông)"]},

{kanji:"先生",hira:"せんせい",kata:"",romaji:"sensei",pos:"Danh từ",level:"N5",topic:"Trường học",
 vi:["giáo viên","thầy/cô"],en:["teacher"],jp:"教える人。",
 examples:[{jp:"田中先生は優しいです。",romaji:"Tanaka sensei wa yasashii desu.",vi:"Thầy Tanaka rất hiền."}],
 synonyms:["教師"],compounds:["先生方 (các thầy cô)"]},

{kanji:"友達",hira:"ともだち",kata:"",romaji:"tomodachi",pos:"Danh từ",level:"N5",topic:"Con người",
 vi:["bạn bè"],en:["friend"],jp:"仲がいい人。",
 examples:[{jp:"友達と映画を見ます。",romaji:"Tomodachi to eiga wo mimasu.",vi:"Tôi xem phim với bạn."}],
 synonyms:["友人"],compounds:["友達関係 (mối quan hệ bạn bè)"]},

{kanji:"大丈夫",hira:"だいじょうぶ",kata:"",romaji:"daijoubu",pos:"Tính từ na",level:"N5",topic:"Giao tiếp",
 vi:["không sao","ổn"],en:["fine, okay"],jp:"問題がない様子。",
 examples:[{jp:"大丈夫ですか。",romaji:"Daijoubu desu ka.",vi:"Bạn ổn không?"}],
 synonyms:["平気"],compounds:[]},

{kanji:"勉強",hira:"べんきょう",kata:"",romaji:"benkyou",pos:"Danh từ / Suru-động từ",level:"N5",topic:"Học tập",
 vi:["học tập","sự học"],en:["study"],jp:"知識や技術を学ぶこと。",
 examples:[{jp:"日本語を勉強しています。",romaji:"Nihongo wo benkyou shite imasu.",vi:"Tôi đang học tiếng Nhật."}],
 synonyms:["学習"],compounds:["勉強家 (người ham học)"]},

{kanji:"仕事",hira:"しごと",kata:"",romaji:"shigoto",pos:"Danh từ",level:"N5",topic:"Công việc",
 vi:["công việc"],en:["job, work"],jp:"生活のためにする作業。",
 examples:[{jp:"仕事は忙しいです。",romaji:"Shigoto wa isogashii desu.",vi:"Công việc bận rộn."}],
 synonyms:["職業"],compounds:["仕事場 (nơi làm việc)"]},

{kanji:"electron_placeholder",hira:"",kata:"",romaji:"",pos:"",level:"",topic:"",vi:[],en:[],jp:"",examples:[],synonyms:[],compounds:[]},

{kanji:"時間",hira:"じかん",kata:"",romaji:"jikan",pos:"Danh từ",level:"N5",topic:"Thời gian",
 vi:["thời gian"],en:["time"],jp:"時の長さ。",
 examples:[{jp:"時間がありません。",romaji:"Jikan ga arimasen.",vi:"Không có thời gian."}],
 synonyms:[],compounds:["時間割 (thời khóa biểu)"]},

{kanji:"元気",hira:"げんき",kata:"",romaji:"genki",pos:"Tính từ na",level:"N5",topic:"Sức khỏe",
 vi:["khỏe mạnh","tràn đầy năng lượng"],en:["healthy, energetic"],jp:"体や心が健康で活発な様子。",
 examples:[{jp:"お元気ですか。",romaji:"Ogenki desu ka.",vi:"Bạn khỏe không?"}],
 synonyms:["健康"],compounds:[]},

{kanji:"難しい",hira:"むずかしい",kata:"",romaji:"muzukashii",pos:"Tính từ i",level:"N4",topic:"Tính chất",
 vi:["khó"],en:["difficult"],jp:"簡単にできない様子。",
 examples:[{jp:"漢字は難しいです。",romaji:"Kanji wa muzukashii desu.",vi:"Kanji rất khó."}],
 synonyms:[],compounds:[]},

{kanji:"約束",hira:"やくそく",kata:"",romaji:"yakusoku",pos:"Danh từ / Suru-động từ",level:"N4",topic:"Giao tiếp",
 vi:["lời hứa","hẹn"],en:["promise, appointment"],jp:"必ずすると決めること。",
 examples:[{jp:"友達と約束をしました。",romaji:"Tomodachi to yakusoku wo shimashita.",vi:"Tôi đã hẹn với bạn."}],
 synonyms:[],compounds:["約束の時間 (giờ hẹn)"]},

{kanji:"経験",hira:"けいけん",kata:"",romaji:"keiken",pos:"Danh từ / Suru-động từ",level:"N3",topic:"Cuộc sống",
 vi:["kinh nghiệm","trải nghiệm"],en:["experience"],jp:"実際に見たりしたりして得た知識。",
 examples:[{jp:"日本で働いた経験があります。",romaji:"Nihon de hataraita keiken ga arimasu.",vi:"Tôi có kinh nghiệm làm việc ở Nhật."}],
 synonyms:[],compounds:[]},

{kanji:"影響",hira:"えいきょう",kata:"",romaji:"eikyou",pos:"Danh từ / Suru-động từ",level:"N3",topic:"Xã hội",
 vi:["ảnh hưởng"],en:["influence, effect"],jp:"他のものに変化を与えること。",
 examples:[{jp:"天気は気分に影響します。",romaji:"Tenki wa kibun ni eikyou shimasu.",vi:"Thời tiết ảnh hưởng đến tâm trạng."}],
 synonyms:[],compounds:[]},

{kanji:"美味しい",hira:"おいしい",kata:"",romaji:"oishii",pos:"Tính từ i",level:"N5",topic:"Ăn uống",
 vi:["ngon"],en:["delicious"],jp:"味がよい様子。",
 examples:[{jp:"このラーメンは美味しいです。",romaji:"Kono raamen wa oishii desu.",vi:"Ramen này ngon."}],
 synonyms:["うまい"],compounds:[]},

{kanji:"病院",hira:"びょういん",kata:"",romaji:"byouin",pos:"Danh từ",level:"N5",topic:"Sức khỏe",
 vi:["bệnh viện"],en:["hospital"],jp:"病気を治す場所。",
 examples:[{jp:"病院へ行きます。",romaji:"Byouin e ikimasu.",vi:"Tôi đi bệnh viện."}],
 synonyms:[],compounds:[]},

{kanji:"電車",hira:"でんしゃ",kata:"",romaji:"densha",pos:"Danh từ",level:"N5",topic:"Giao thông",
 vi:["tàu điện"],en:["train"],jp:"電気で走る乗り物。",
 examples:[{jp:"電車で会社へ行きます。",romaji:"Densha de kaisha e ikimasu.",vi:"Tôi đi làm bằng tàu điện."}],
 synonyms:[],compounds:["電車代 (tiền vé tàu)"]},

{kanji:"忙しい",hira:"いそがしい",kata:"",romaji:"isogashii",pos:"Tính từ i",level:"N5",topic:"Công việc",
 vi:["bận rộn"],en:["busy"],jp:"することが多くて時間がない様子。",
 examples:[{jp:"今週は忙しいです。",romaji:"Konshuu wa isogashii desu.",vi:"Tuần này tôi bận."}],
 synonyms:[],compounds:[]},

{kanji:"約束を守る",hira:"やくそくをまもる",kata:"",romaji:"yakusoku wo mamoru",pos:"Cụm động từ",level:"N4",topic:"Giao tiếp",
 vi:["giữ lời hứa"],en:["to keep a promise"],jp:"約束したことを実行する。",
 examples:[{jp:"約束を守ってください。",romaji:"Yakusoku wo mamotte kudasai.",vi:"Hãy giữ lời hứa."}],
 synonyms:[],compounds:[]},

{kanji:"環境",hira:"かんきょう",kata:"",romaji:"kankyou",pos:"Danh từ",level:"N3",topic:"Xã hội",
 vi:["môi trường"],en:["environment"],jp:"人や生き物を取り巻く周りのもの。",
 examples:[{jp:"環境を守りましょう。",romaji:"Kankyou wo mamorimashou.",vi:"Hãy bảo vệ môi trường."}],
 synonyms:[],compounds:["環境問題 (vấn đề môi trường)"]},

{kanji:"解決",hira:"かいけつ",kata:"",romaji:"kaiketsu",pos:"Danh từ / Suru-động từ",level:"N2",topic:"Xã hội",
 vi:["giải quyết"],en:["solution, resolution"],jp:"問題をなくすこと。",
 examples:[{jp:"問題を解決しました。",romaji:"Mondai wo kaiketsu shimashita.",vi:"Tôi đã giải quyết vấn đề."}],
 synonyms:[],compounds:[]},

{kanji:"矛盾",hira:"むじゅん",kata:"",romaji:"mujun",pos:"Danh từ / Suru-động từ",level:"N1",topic:"Tư duy",
 vi:["mâu thuẫn"],en:["contradiction"],jp:"二つのことが合わないこと。",
 examples:[{jp:"彼の話は矛盾しています。",romaji:"Kare no hanashi wa mujun shite imasu.",vi:"Lời nói của anh ấy mâu thuẫn."}],
 synonyms:[],compounds:[]},

{kanji:"猫",hira:"ねこ",kata:"ネコ",romaji:"neko",pos:"Danh từ",level:"N5",topic:"Động vật",
 vi:["con mèo"],en:["cat"],jp:"ペットとして人気がある動物。",
 examples:[{jp:"猫が好きです。",romaji:"Neko ga suki desu.",vi:"Tôi thích mèo."}],
 synonyms:[],compounds:[]},

{kanji:"水",hira:"みず",kata:"",romaji:"mizu",pos:"Danh từ",level:"N5",topic:"Tự nhiên",
 vi:["nước"],en:["water"],jp:"透明な液体。",
 examples:[{jp:"水をください。",romaji:"Mizu wo kudasai.",vi:"Cho tôi xin nước."}],
 synonyms:[],compounds:["水道 (nước máy)"]},

{kanji:"雨",hira:"あめ",kata:"",romaji:"ame",pos:"Danh từ",level:"N5",topic:"Thời tiết",
 vi:["mưa"],en:["rain"],jp:"空から降る水。",
 examples:[{jp:"今日は雨です。",romaji:"Kyou wa ame desu.",vi:"Hôm nay trời mưa."}],
 synonyms:[],compounds:["雨傘 (ô đi mưa)"]},

{kanji:"心配",hira:"しんぱい",kata:"",romaji:"shinpai",pos:"Danh từ / Suru-động từ",level:"N4",topic:"Cảm xúc",
 vi:["lo lắng"],en:["worry"],jp:"悪いことが起きるかもしれないと思うこと。",
 examples:[{jp:"心配しないでください。",romaji:"Shinpai shinaide kudasai.",vi:"Đừng lo lắng."}],
 synonyms:[],compounds:[]},

{kanji:"嬉しい",hira:"うれしい",kata:"",romaji:"ureshii",pos:"Tính từ i",level:"N4",topic:"Cảm xúc",
 vi:["vui mừng"],en:["happy, glad"],jp:"よいことがあって喜ぶ様子。",
 examples:[{jp:"会えて嬉しいです。",romaji:"Aete ureshii desu.",vi:"Rất vui được gặp bạn."}],
 synonyms:["楽しい"],compounds:[]},

{kanji:"悲しい",hira:"かなしい",kata:"",romaji:"kanashii",pos:"Tính từ i",level:"N4",topic:"Cảm xúc",
 vi:["buồn"],en:["sad"],jp:"心が痛む様子。",
 examples:[{jp:"別れは悲しいです。",romaji:"Wakare wa kanashii desu.",vi:"Chia ly thật buồn."}],
 synonyms:[],compounds:[]},

{kanji:"働く",hira:"はたらく",kata:"",romaji:"hataraku",pos:"Động từ nhóm 1",level:"N4",topic:"Công việc",
 vi:["làm việc"],en:["to work"],jp:"仕事をすること。",
 examples:[{jp:"会社で働いています。",romaji:"Kaisha de hataraite imasu.",vi:"Tôi làm việc ở công ty."}],
 synonyms:[],compounds:[]},

{kanji:"始める",hira:"はじめる",kata:"",romaji:"hajimeru",pos:"Động từ nhóm 2",level:"N5",topic:"Hành động",
 vi:["bắt đầu"],en:["to begin"],jp:"物事をスタートすること。",
 examples:[{jp:"授業を始めます。",romaji:"Jugyou wo hajimemasu.",vi:"Bắt đầu tiết học."}],
 synonyms:[],compounds:[]},

{kanji:"終わる",hira:"おわる",kata:"",romaji:"owaru",pos:"Động từ nhóm 1",level:"N5",topic:"Hành động",
 vi:["kết thúc"],en:["to end"],jp:"物事が終了すること。",
 examples:[{jp:"仕事が終わりました。",romaji:"Shigoto ga owarimashita.",vi:"Công việc đã kết thúc."}],
 synonyms:[],compounds:[]},

{kanji:"駅",hira:"えき",kata:"",romaji:"eki",pos:"Danh từ",level:"N5",topic:"Giao thông",
 vi:["nhà ga"],en:["station"],jp:"電車が止まる場所。",
 examples:[{jp:"駅まで歩きます。",romaji:"Eki made arukimasu.",vi:"Tôi đi bộ đến ga."}],
 synonyms:[],compounds:[]},

{kanji:"買い物",hira:"かいもの",kata:"",romaji:"kaimono",pos:"Danh từ",level:"N5",topic:"Mua sắm",
 vi:["mua sắm"],en:["shopping"],jp:"物を買うこと。",
 examples:[{jp:"買い物に行きます。",romaji:"Kaimono ni ikimasu.",vi:"Tôi đi mua sắm."}],
 synonyms:[],compounds:[]},

{kanji:"旅行",hira:"りょこう",kata:"",romaji:"ryokou",pos:"Danh từ / Suru-động từ",level:"N4",topic:"Du lịch",
 vi:["du lịch"],en:["travel, trip"],jp:"よその土地へ行くこと。",
 examples:[{jp:"日本へ旅行しました。",romaji:"Nihon e ryokou shimashita.",vi:"Tôi đã đi du lịch Nhật Bản."}],
 synonyms:[],compounds:[]},

{kanji:"締め切り",hira:"しめきり",kata:"",romaji:"shimekiri",pos:"Danh từ",level:"N2",topic:"Công việc",
 vi:["hạn chót"],en:["deadline"],jp:"物事を終わらせなければならない期限。",
 examples:[{jp:"締め切りに間に合いました。",romaji:"Shimekiri ni maniaimashita.",vi:"Tôi đã kịp hạn chót."}],
 synonyms:[],compounds:[]},

{kanji:"想像",hira:"そうぞう",kata:"",romaji:"souzou",pos:"Danh từ / Suru-động từ",level:"N3",topic:"Tư duy",
 vi:["tưởng tượng"],en:["imagination"],jp:"頭の中で考えて思い浮かべること。",
 examples:[{jp:"未来を想像します。",romaji:"Mirai wo souzou shimasu.",vi:"Tôi tưởng tượng về tương lai."}],
 synonyms:[],compounds:[]},

{kanji:"優先",hira:"ゆうせん",kata:"",romaji:"yuusen",pos:"Danh từ / Suru-động từ",level:"N2",topic:"Xã hội",
 vi:["ưu tiên"],en:["priority"],jp:"他よりも先に扱うこと。",
 examples:[{jp:"安全を優先します。",romaji:"Anzen wo yuusen shimasu.",vi:"Ưu tiên sự an toàn."}],
 synonyms:[],compounds:[]},

{kanji:"曖昧",hira:"あいまい",kata:"",romaji:"aimai",pos:"Tính từ na",level:"N1",topic:"Tư duy",
 vi:["mơ hồ","mập mờ"],en:["ambiguous, vague"],jp:"はっきりしない様子。",
 examples:[{jp:"曖昧な返事をしました。",romaji:"Aimai na henji wo shimashita.",vi:"Tôi đã trả lời mập mờ."}],
 synonyms:[],compounds:[]},

{kanji:"配慮",hira:"はいりょ",kata:"",romaji:"hairyo",pos:"Danh từ / Suru-động từ",level:"N1",topic:"Xã hội",
 vi:["quan tâm chu đáo","cân nhắc"],en:["consideration"],jp:"他人のために心を配ること。",
 examples:[{jp:"周りへの配慮が大切です。",romaji:"Mawari e no hairyo ga taisetsu desu.",vi:"Quan tâm đến mọi người xung quanh là quan trọng."}],
 synonyms:[],compounds:[]},

{kanji:"綺麗",hira:"きれい",kata:"",romaji:"kirei",pos:"Tính từ na",level:"N5",topic:"Tính chất",
 vi:["đẹp","sạch sẽ"],en:["beautiful, clean"],jp:"見た目が美しい、または清潔な様子。",
 examples:[{jp:"部屋が綺麗です。",romaji:"Heya ga kirei desu.",vi:"Căn phòng sạch sẽ."}],
 synonyms:[],compounds:[]},

{kanji:"静か",hira:"しずか",kata:"",romaji:"shizuka",pos:"Tính từ na",level:"N5",topic:"Tính chất",
 vi:["yên tĩnh"],en:["quiet"],jp:"音がなく穏やかな様子。",
 examples:[{jp:"図書館は静かです。",romaji:"Toshokan wa shizuka desu.",vi:"Thư viện yên tĩnh."}],
 synonyms:[],compounds:[]},

{kanji:"頑張る",hira:"がんばる",kata:"",romaji:"ganbaru",pos:"Động từ nhóm 1",level:"N4",topic:"Tinh thần",
 vi:["cố gắng"],en:["to try hard, do one's best"],jp:"努力すること。",
 examples:[{jp:"試験、頑張ってください。",romaji:"Shiken, ganbatte kudasai.",vi:"Cố gắng thi tốt nhé."}],
 synonyms:[],compounds:[]},

{kanji:"諦める",hira:"あきらめる",kata:"",romaji:"akirameru",pos:"Động từ nhóm 2",level:"N3",topic:"Tinh thần",
 vi:["từ bỏ"],en:["to give up"],jp:"望みや目標をやめること。",
 examples:[{jp:"夢を諦めないでください。",romaji:"Yume wo akiramenaide kudasai.",vi:"Đừng từ bỏ ước mơ."}],
 synonyms:[],compounds:[]},

{kanji:"信頼",hira:"しんらい",kata:"",romaji:"shinrai",pos:"Danh từ / Suru-động từ",level:"N2",topic:"Con người",
 vi:["tin tưởng"],en:["trust"],jp:"信じて頼ること。",
 examples:[{jp:"彼を信頼しています。",romaji:"Kare wo shinrai shite imasu.",vi:"Tôi tin tưởng anh ấy."}],
 synonyms:[],compounds:[]},

{kanji:"注意",hira:"ちゅうい",kata:"",romaji:"chuui",pos:"Danh từ / Suru-động từ",level:"N4",topic:"Giao tiếp",
 vi:["chú ý","cẩn thận"],en:["caution, attention"],jp:"気をつけること。",
 examples:[{jp:"車に注意してください。",romaji:"Kuruma ni chuui shite kudasai.",vi:"Hãy cẩn thận với xe cộ."}],
 synonyms:[],compounds:[]},

{kanji:"郵便局",hira:"ゆうびんきょく",kata:"",romaji:"yuubinkyoku",pos:"Danh từ",level:"N4",topic:"Địa điểm",
 vi:["bưu điện"],en:["post office"],jp:"手紙や荷物を送る場所。",
 examples:[{jp:"郵便局で切手を買います。",romaji:"Yuubinkyoku de kitte wo kaimasu.",vi:"Tôi mua tem ở bưu điện."}],
 synonyms:[],compounds:[]},

{kanji:"寂しい",hira:"さびしい",kata:"",romaji:"sabishii",pos:"Tính từ i",level:"N3",topic:"Cảm xúc",
 vi:["cô đơn"],en:["lonely"],jp:"一人で心が満たされない様子。",
 examples:[{jp:"一人で寂しいです。",romaji:"Hitori de sabishii desu.",vi:"Một mình thấy cô đơn."}],
 synonyms:[],compounds:[]},

{kanji:"挑戦",hira:"ちょうせん",kata:"",romaji:"chousen",pos:"Danh từ / Suru-động từ",level:"N3",topic:"Tinh thần",
 vi:["thử thách"],en:["challenge"],jp:"難しいことに立ち向かうこと。",
 examples:[{jp:"新しいことに挑戦します。",romaji:"Atarashii koto ni chousen shimasu.",vi:"Tôi thử thách bản thân với điều mới."}],
 synonyms:[],compounds:[]},

// ===== Bổ sung thêm từ vựng (mở rộng độ phủ N5→N1) =====
{kanji:"改善",hira:"かいぜん",kata:"",romaji:"kaizen",pos:"Danh từ / Suru-động từ",level:"N2",topic:"Xã hội",
 vi:["cải thiện"],en:["improvement"],jp:"悪い所を良くすること。",
 examples:[{jp:"サービスを改善します。",romaji:"Saabisu wo kaizen shimasu.",vi:"Chúng tôi sẽ cải thiện dịch vụ."}],synonyms:[],compounds:[]},
{kanji:"普及",hira:"ふきゅう",kata:"",romaji:"fukyuu",pos:"Danh từ / Suru-động từ",level:"N2",topic:"Xã hội",
 vi:["phổ biến (lan rộng)"],en:["spread, popularization"],jp:"広く行き渡ること。",
 examples:[{jp:"スマホが普及しました。",romaji:"Sumaho ga fukyuu shimashita.",vi:"Điện thoại thông minh đã trở nên phổ biến."}],synonyms:[],compounds:[]},
{kanji:"依然として",hira:"いぜんとして",kata:"",romaji:"izen toshite",pos:"Trạng từ",level:"N2",topic:"Tư duy",
 vi:["vẫn còn như cũ"],en:["still, as before"],jp:"前と変わらない様子。",
 examples:[{jp:"依然として問題は解決していません。",romaji:"Izen toshite mondai wa kaiketsu shite imasen.",vi:"Vấn đề vẫn chưa được giải quyết."}],synonyms:[],compounds:[]},
{kanji:"重視",hira:"じゅうし",kata:"",romaji:"juushi",pos:"Danh từ / Suru-động từ",level:"N2",topic:"Tư duy",
 vi:["coi trọng"],en:["to emphasize, value"],jp:"大切だと考えること。",
 examples:[{jp:"健康を重視しています。",romaji:"Kenkou wo juushi shite imasu.",vi:"Tôi coi trọng sức khỏe."}],synonyms:[],compounds:[]},
{kanji:"模索",hira:"もさく",kata:"",romaji:"mosaku",pos:"Danh từ / Suru-động từ",level:"N1",topic:"Tư duy",
 vi:["dò dẫm tìm kiếm"],en:["groping for, exploring"],jp:"よい方法を探すこと。",
 examples:[{jp:"新しい方法を模索しています。",romaji:"Atarashii houhou wo mosaku shite imasu.",vi:"Tôi đang dò dẫm tìm phương pháp mới."}],synonyms:[],compounds:[]},
{kanji:"価値観",hira:"かちかん",kata:"",romaji:"kachikan",pos:"Danh từ",level:"N2",topic:"Xã hội",
 vi:["giá trị quan"],en:["values, sense of values"],jp:"何が大切かという考え方。",
 examples:[{jp:"価値観は人それぞれです。",romaji:"Kachikan wa hito sorezore desu.",vi:"Giá trị quan của mỗi người mỗi khác."}],synonyms:[],compounds:[]},
{kanji:"終身雇用",hira:"しゅうしんこよう",kata:"",romaji:"shuushin koyou",pos:"Danh từ",level:"N1",topic:"Công việc",
 vi:["chế độ tuyển dụng suốt đời"],en:["lifetime employment"],jp:"退職まで同じ会社で働く制度。",
 examples:[{jp:"終身雇用は減っています。",romaji:"Shuushin koyou wa hette imasu.",vi:"Chế độ tuyển dụng suốt đời đang giảm."}],synonyms:[],compounds:[]},
{kanji:"転職",hira:"てんしょく",kata:"",romaji:"tenshoku",pos:"Danh từ / Suru-động từ",level:"N3",topic:"Công việc",
 vi:["chuyển việc"],en:["job change"],jp:"別の会社に移って働くこと。",
 examples:[{jp:"来月転職します。",romaji:"Raigetsu tenshoku shimasu.",vi:"Tháng sau tôi sẽ chuyển việc."}],synonyms:[],compounds:[]},
{kanji:"深刻",hira:"しんこく",kata:"",romaji:"shinkoku",pos:"Tính từ na",level:"N3",topic:"Xã hội",
 vi:["nghiêm trọng"],en:["serious"],jp:"事態が非常に悪い様子。",
 examples:[{jp:"問題が深刻になっています。",romaji:"Mondai ga shinkoku ni natte imasu.",vi:"Vấn đề đang trở nên nghiêm trọng."}],synonyms:[],compounds:[]},
{kanji:"温暖化",hira:"おんだんか",kata:"",romaji:"ondanka",pos:"Danh từ",level:"N3",topic:"Tự nhiên",
 vi:["hiện tượng ấm lên"],en:["warming"],jp:"気温が高くなっていくこと。",
 examples:[{jp:"地球温暖化が進んでいます。",romaji:"Chikyuu ondanka ga susunde imasu.",vi:"Hiện tượng nóng lên toàn cầu đang tiến triển."}],synonyms:[],compounds:[]},
{kanji:"異常",hira:"いじょう",kata:"",romaji:"ijou",pos:"Tính từ na / Danh từ",level:"N3",topic:"Tự nhiên",
 vi:["bất thường"],en:["abnormal"],jp:"普通ではない様子。",
 examples:[{jp:"異常気象が続いています。",romaji:"Ijou kishou ga tsuzuite imasu.",vi:"Thời tiết bất thường vẫn tiếp diễn."}],synonyms:[],compounds:[]},
{kanji:"公共",hira:"こうきょう",kata:"",romaji:"koukyou",pos:"Danh từ",level:"N3",topic:"Xã hội",
 vi:["công cộng"],en:["public"],jp:"社会全体に関わること。",
 examples:[{jp:"公共交通機関を利用します。",romaji:"Koukyou koutsuu kikan wo riyou shimasu.",vi:"Tôi sử dụng phương tiện giao thông công cộng."}],synonyms:[],compounds:[]},
{kanji:"矛盾する",hira:"むじゅんする",kata:"",romaji:"mujun suru",pos:"Suru-động từ",level:"N1",topic:"Tư duy",
 vi:["mâu thuẫn"],en:["to contradict"],jp:"二つのことが合わないこと。",
 examples:[{jp:"言っていることが矛盾しています。",romaji:"Itte iru koto ga mujun shite imasu.",vi:"Những gì anh ấy nói đang mâu thuẫn."}],synonyms:[],compounds:[]},
{kanji:"曖昧にする",hira:"あいまいにする",kata:"",romaji:"aimai ni suru",pos:"Cụm động từ",level:"N1",topic:"Giao tiếp",
 vi:["làm cho mập mờ"],en:["to make ambiguous"],jp:"はっきりさせないこと。",
 examples:[{jp:"答えを曖昧にしないでください。",romaji:"Kotae wo aimai ni shinaide kudasai.",vi:"Đừng trả lời mập mờ."}],synonyms:[],compounds:[]},
{kanji:"疑う",hira:"うたがう",kata:"",romaji:"utagau",pos:"Động từ nhóm 1",level:"N3",topic:"Tư duy",
 vi:["nghi ngờ"],en:["to doubt"],jp:"本当かどうか信じられないと思うこと。",
 examples:[{jp:"彼の話を疑っています。",romaji:"Kare no hanashi wo utagatte imasu.",vi:"Tôi đang nghi ngờ lời của anh ấy."}],synonyms:[],compounds:[]},
{kanji:"実現",hira:"じつげん",kata:"",romaji:"jitsugen",pos:"Danh từ / Suru-động từ",level:"N2",topic:"Tư duy",
 vi:["hiện thực hóa"],en:["realization"],jp:"考えたことを実際にすること。",
 examples:[{jp:"夢を実現しました。",romaji:"Yume wo jitsugen shimashita.",vi:"Tôi đã hiện thực hóa ước mơ."}],synonyms:[],compounds:[]},
{kanji:"否定",hira:"ひてい",kata:"",romaji:"hitei",pos:"Danh từ / Suru-động từ",level:"N2",topic:"Tư duy",
 vi:["phủ định"],en:["denial, negation"],jp:"そうではないと言うこと。",
 examples:[{jp:"事実を否定できません。",romaji:"Jijitsu wo hitei dekimasen.",vi:"Không thể phủ định sự thật."}],synonyms:[],compounds:[]},
{kanji:"肯定",hira:"こうてい",kata:"",romaji:"koutei",pos:"Danh từ / Suru-động từ",level:"N2",topic:"Tư duy",
 vi:["khẳng định"],en:["affirmation"],jp:"そうだと認めること。",
 examples:[{jp:"彼の意見を肯定します。",romaji:"Kare no iken wo koutei shimasu.",vi:"Tôi khẳng định (đồng ý với) ý kiến của anh ấy."}],synonyms:[],compounds:[]},
{kanji:"抽象的",hira:"ちゅうしょうてき",kata:"",romaji:"chuushouteki",pos:"Tính từ na",level:"N1",topic:"Tư duy",
 vi:["trừu tượng"],en:["abstract"],jp:"具体的でない様子。",
 examples:[{jp:"説明が抽象的すぎます。",romaji:"Setsumei ga chuushouteki sugimasu.",vi:"Lời giải thích quá trừu tượng."}],synonyms:[],compounds:[]},
{kanji:"具体的",hira:"ぐたいてき",kata:"",romaji:"gutaiteki",pos:"Tính từ na",level:"N2",topic:"Tư duy",
 vi:["cụ thể"],en:["concrete, specific"],jp:"はっきりしている様子。",
 examples:[{jp:"具体的な例を教えてください。",romaji:"Gutaiteki na rei wo oshiete kudasai.",vi:"Hãy cho tôi ví dụ cụ thể."}],synonyms:[],compounds:[]},
{kanji:"率直",hira:"そっちょく",kata:"",romaji:"socchoku",pos:"Tính từ na",level:"N1",topic:"Tính chất",
 vi:["thẳng thắn"],en:["frank, candid"],jp:"隠さずに正直に言う様子。",
 examples:[{jp:"率直な意見をお願いします。",romaji:"Socchoku na iken wo onegaishimasu.",vi:"Xin cho tôi ý kiến thẳng thắn."}],synonyms:[],compounds:[]},
{kanji:"謙虚",hira:"けんきょ",kata:"",romaji:"kenkyo",pos:"Tính từ na",level:"N1",topic:"Tính chất",
 vi:["khiêm tốn"],en:["humble"],jp:"控えめで威張らない様子。",
 examples:[{jp:"彼はいつも謙虚です。",romaji:"Kare wa itsumo kenkyo desu.",vi:"Anh ấy lúc nào cũng khiêm tốn."}],synonyms:[],compounds:[]},
{kanji:"贅沢",hira:"ぜいたく",kata:"",romaji:"zeitaku",pos:"Tính từ na / Danh từ",level:"N2",topic:"Cuộc sống",
 vi:["xa xỉ"],en:["luxury"],jp:"必要以上にお金を使う様子。",
 examples:[{jp:"贅沢な生活をしています。",romaji:"Zeitaku na seikatsu wo shite imasu.",vi:"Tôi đang sống một cuộc sống xa xỉ."}],synonyms:[],compounds:[]},
{kanji:"倹約",hira:"けんやく",kata:"",romaji:"ken'yaku",pos:"Danh từ / Suru-động từ",level:"N1",topic:"Cuộc sống",
 vi:["tiết kiệm"],en:["thrift, frugality"],jp:"むだ遣いをしないこと。",
 examples:[{jp:"倹約して貯金します。",romaji:"Ken'yaku shite chokin shimasu.",vi:"Tôi tiết kiệm để dành tiền."}],synonyms:[],compounds:[]},
{kanji:"貯金",hira:"ちょきん",kata:"",romaji:"chokin",pos:"Danh từ / Suru-động từ",level:"N3",topic:"Tiền bạc",
 vi:["tiền tiết kiệm"],en:["savings"],jp:"お金をためること。",
 examples:[{jp:"毎月貯金しています。",romaji:"Maitsuki chokin shite imasu.",vi:"Tôi tiết kiệm tiền mỗi tháng."}],synonyms:[],compounds:[]},
{kanji:"税金",hira:"ぜいきん",kata:"",romaji:"zeikin",pos:"Danh từ",level:"N3",topic:"Tiền bạc",
 vi:["thuế"],en:["tax"],jp:"国や自治体に納めるお金。",
 examples:[{jp:"税金を払います。",romaji:"Zeikin wo haraimasu.",vi:"Tôi đóng thuế."}],synonyms:[],compounds:[]},
{kanji:"景気",hira:"けいき",kata:"",romaji:"keiki",pos:"Danh từ",level:"N2",topic:"Kinh tế",
 vi:["tình hình kinh tế"],en:["economic conditions"],jp:"経済の状態。",
 examples:[{jp:"景気が良くなっています。",romaji:"Keiki ga yoku natte imasu.",vi:"Tình hình kinh tế đang tốt lên."}],synonyms:[],compounds:[]},
{kanji:"不況",hira:"ふきょう",kata:"",romaji:"fukyou",pos:"Danh từ",level:"N1",topic:"Kinh tế",
 vi:["suy thoái kinh tế"],en:["recession"],jp:"景気が悪い状態。",
 examples:[{jp:"不況が続いています。",romaji:"Fukyou ga tsuzuite imasu.",vi:"Suy thoái kinh tế vẫn tiếp diễn."}],synonyms:[],compounds:[]},
{kanji:"就職",hira:"しゅうしょく",kata:"",romaji:"shuushoku",pos:"Danh từ / Suru-động từ",level:"N3",topic:"Công việc",
 vi:["xin việc, đi làm"],en:["getting a job"],jp:"会社などに勤めること。",
 examples:[{jp:"来年就職します。",romaji:"Rainen shuushoku shimasu.",vi:"Sang năm tôi sẽ đi làm."}],synonyms:[],compounds:[]},
{kanji:"退職",hira:"たいしょく",kata:"",romaji:"taishoku",pos:"Danh từ / Suru-động từ",level:"N2",topic:"Công việc",
 vi:["nghỉ hưu, nghỉ việc"],en:["retirement, resignation"],jp:"仕事をやめること。",
 examples:[{jp:"父は来月退職します。",romaji:"Chichi wa raigetsu taishoku shimasu.",vi:"Bố tôi sẽ nghỉ hưu vào tháng sau."}],synonyms:[],compounds:[]},
{kanji:"昇進",hira:"しょうしん",kata:"",romaji:"shoushin",pos:"Danh từ / Suru-động từ",level:"N1",topic:"Công việc",
 vi:["thăng chức"],en:["promotion"],jp:"仕事の地位が上がること。",
 examples:[{jp:"部長に昇進しました。",romaji:"Buchou ni shoushin shimashita.",vi:"Tôi đã được thăng chức làm trưởng phòng."}],synonyms:[],compounds:[]},
{kanji:"責任",hira:"せきにん",kata:"",romaji:"sekinin",pos:"Danh từ",level:"N3",topic:"Công việc",
 vi:["trách nhiệm"],en:["responsibility"],jp:"果たすべき義務。",
 examples:[{jp:"責任を持って仕事をします。",romaji:"Sekinin wo motte shigoto wo shimasu.",vi:"Tôi làm việc với trách nhiệm."}],synonyms:[],compounds:[]},
{kanji:"義務",hira:"ぎむ",kata:"",romaji:"gimu",pos:"Danh từ",level:"N2",topic:"Xã hội",
 vi:["nghĩa vụ"],en:["duty, obligation"],jp:"しなければならないこと。",
 examples:[{jp:"税金を納める義務があります。",romaji:"Zeikin wo osameru gimu ga arimasu.",vi:"Có nghĩa vụ đóng thuế."}],synonyms:[],compounds:[]},
{kanji:"権利",hira:"けんり",kata:"",romaji:"kenri",pos:"Danh từ",level:"N2",topic:"Xã hội",
 vi:["quyền lợi"],en:["right"],jp:"当然主張できること。",
 examples:[{jp:"投票する権利があります。",romaji:"Touhyou suru kenri ga arimasu.",vi:"Có quyền bỏ phiếu."}],synonyms:[],compounds:[]},
{kanji:"法律",hira:"ほうりつ",kata:"",romaji:"houritsu",pos:"Danh từ",level:"N3",topic:"Xã hội",
 vi:["pháp luật"],en:["law"],jp:"国が決めたルール。",
 examples:[{jp:"法律を守らなければなりません。",romaji:"Houritsu wo mamoranakereba narimasen.",vi:"Phải tuân thủ pháp luật."}],synonyms:[],compounds:[]},
{kanji:"違反",hira:"いはん",kata:"",romaji:"ihan",pos:"Danh từ / Suru-động từ",level:"N2",topic:"Xã hội",
 vi:["vi phạm"],en:["violation"],jp:"規則を破ること。",
 examples:[{jp:"交通違反をしました。",romaji:"Koutsuu ihan wo shimashita.",vi:"Tôi đã vi phạm giao thông."}],synonyms:[],compounds:[]},
{kanji:"検討",hira:"けんとう",kata:"",romaji:"kentou",pos:"Danh từ / Suru-động từ",level:"N2",topic:"Công việc",
 vi:["xem xét, cân nhắc"],en:["consideration, examination"],jp:"よく考えること。",
 examples:[{jp:"その案を検討します。",romaji:"Sono an wo kentou shimasu.",vi:"Tôi sẽ xem xét đề án đó."}],synonyms:[],compounds:[]},
{kanji:"提案",hira:"ていあん",kata:"",romaji:"teian",pos:"Danh từ / Suru-động từ",level:"N2",topic:"Công việc",
 vi:["đề xuất"],en:["proposal"],jp:"考えを出して勧めること。",
 examples:[{jp:"新しい提案をします。",romaji:"Atarashii teian wo shimasu.",vi:"Tôi sẽ đưa ra đề xuất mới."}],synonyms:[],compounds:[]},
{kanji:"承認",hira:"しょうにん",kata:"",romaji:"shounin",pos:"Danh từ / Suru-động từ",level:"N1",topic:"Công việc",
 vi:["phê duyệt"],en:["approval"],jp:"正しいと認めること。",
 examples:[{jp:"計画が承認されました。",romaji:"Keikaku ga shounin saremashita.",vi:"Kế hoạch đã được phê duyệt."}],synonyms:[],compounds:[]},
{kanji:"妥協",hira:"だきょう",kata:"",romaji:"dakyou",pos:"Danh từ / Suru-động từ",level:"N1",topic:"Giao tiếp",
 vi:["thỏa hiệp"],en:["compromise"],jp:"お互いに譲り合うこと。",
 examples:[{jp:"妥協点を探しましょう。",romaji:"Dakyouten wo sagashimashou.",vi:"Hãy cùng tìm điểm thỏa hiệp."}],synonyms:[],compounds:[]},
{kanji:"譲る",hira:"ゆずる",kata:"",romaji:"yuzuru",pos:"Động từ nhóm 1",level:"N2",topic:"Giao tiếp",
 vi:["nhường"],en:["to yield, to give way"],jp:"自分のものや権利を他人にあげること。",
 examples:[{jp:"席を譲りました。",romaji:"Seki wo yuzurimashita.",vi:"Tôi đã nhường chỗ ngồi."}],synonyms:[],compounds:[]},
{kanji:"我慢",hira:"がまん",kata:"",romaji:"gaman",pos:"Danh từ / Suru-động từ",level:"N3",topic:"Tinh thần",
 vi:["nhẫn nhịn, chịu đựng"],en:["patience, endurance"],jp:"辛くても耐えること。",
 examples:[{jp:"痛みを我慢しました。",romaji:"Itami wo gaman shimashita.",vi:"Tôi đã chịu đựng cơn đau."}],synonyms:[],compounds:[]},
{kanji:"忍耐",hira:"にんたい",kata:"",romaji:"nintai",pos:"Danh từ",level:"N1",topic:"Tinh thần",
 vi:["nhẫn nại"],en:["endurance, patience"],jp:"苦しくても我慢し続けること。",
 examples:[{jp:"忍耐力が必要です。",romaji:"Nintai ryoku ga hitsuyou desu.",vi:"Cần có sức nhẫn nại."}],synonyms:["我慢"],compounds:[]},
{kanji:"焦る",hira:"あせる",kata:"",romaji:"aseru",pos:"Động từ nhóm 1",level:"N2",topic:"Cảm xúc",
 vi:["sốt ruột, vội vã"],en:["to be impatient/anxious"],jp:"早くしなければと落ち着かなくなること。",
 examples:[{jp:"試験前で焦っています。",romaji:"Shiken mae de asette imasu.",vi:"Tôi đang sốt ruột vì sắp thi."}],synonyms:[],compounds:[]},
{kanji:"戸惑う",hira:"とまどう",kata:"",romaji:"tomadou",pos:"Động từ nhóm 1",level:"N1",topic:"Cảm xúc",
 vi:["bối rối, lúng túng"],en:["to be confused/perplexed"],jp:"どうすればいいか分からず困ること。",
 examples:[{jp:"急な質問に戸惑いました。",romaji:"Kyuu na shitsumon ni tomadoimashita.",vi:"Tôi bối rối trước câu hỏi bất ngờ."}],synonyms:[],compounds:[]},
{kanji:"励ます",hira:"はげます",kata:"",romaji:"hagemasu",pos:"Động từ nhóm 1",level:"N2",topic:"Giao tiếp",
 vi:["động viên, khích lệ"],en:["to encourage"],jp:"元気づけること。",
 examples:[{jp:"友達を励ましました。",romaji:"Tomodachi wo hagemashimashita.",vi:"Tôi đã động viên bạn mình."}],synonyms:[],compounds:[]},
{kanji:"慰める",hira:"なぐさめる",kata:"",romaji:"nagusameru",pos:"Động từ nhóm 2",level:"N2",topic:"Giao tiếp",
 vi:["an ủi"],en:["to console, comfort"],jp:"悲しんでいる人の心を和らげること。",
 examples:[{jp:"泣いている子を慰めました。",romaji:"Naite iru ko wo nagusamemashita.",vi:"Tôi đã an ủi đứa trẻ đang khóc."}],synonyms:[],compounds:[]},
{kanji:"見落とす",hira:"みおとす",kata:"",romaji:"miotosu",pos:"Động từ nhóm 1",level:"N2",topic:"Hành động",
 vi:["bỏ sót (không để ý)"],en:["to overlook"],jp:"見ているのに気づかないこと。",
 examples:[{jp:"大事な点を見落としました。",romaji:"Daiji na ten wo miotoshimashita.",vi:"Tôi đã bỏ sót điểm quan trọng."}],synonyms:[],compounds:[]},
{kanji:"見直す",hira:"みなおす",kata:"",romaji:"minaosu",pos:"Động từ nhóm 1",level:"N2",topic:"Hành động",
 vi:["xem lại, đánh giá lại"],en:["to review, reconsider"],jp:"もう一度よく見て考えること。",
 examples:[{jp:"計画を見直しましょう。",romaji:"Keikaku wo minaoshimashou.",vi:"Hãy xem lại kế hoạch."}],synonyms:[],compounds:[]},
{kanji:"取り組む",hira:"とりくむ",kata:"",romaji:"torikumu",pos:"Động từ nhóm 1",level:"N2",topic:"Công việc",
 vi:["bắt tay vào giải quyết"],en:["to tackle, work on"],jp:"熱心に物事を行うこと。",
 examples:[{jp:"問題に真剣に取り組んでいます。",romaji:"Mondai ni shinken ni torikunde imasu.",vi:"Tôi đang nghiêm túc giải quyết vấn đề."}],synonyms:[],compounds:[]},
{kanji:"見なす",hira:"みなす",kata:"",romaji:"minasu",pos:"Động từ nhóm 1",level:"N1",topic:"Tư duy",
 vi:["coi như, xem là"],en:["to regard as, deem"],jp:"そのように判断すること。",
 examples:[{jp:"返事がなければ同意とみなします。",romaji:"Henji ga nakereba doui to minashimasu.",vi:"Nếu không trả lời sẽ coi như đồng ý."}],synonyms:[],compounds:[]},
{kanji:"著しい",hira:"いちじるしい",kata:"",romaji:"ichijirushii",pos:"Tính từ i",level:"N1",topic:"Tính chất",
 vi:["rõ rệt, đáng kể"],en:["remarkable, striking"],jp:"はっきりとわかるほど大きい様子。",
 examples:[{jp:"著しい成長が見られます。",romaji:"Ichijirushii seichou ga miraremasu.",vi:"Có thể thấy sự tăng trưởng rõ rệt."}],synonyms:[],compounds:[]},
{kanji:"甚だしい",hira:"はなはだしい",kata:"",romaji:"hanahadashii",pos:"Tính từ i",level:"N1",topic:"Tính chất",
 vi:["quá mức, cực độ"],en:["extreme, excessive"],jp:"程度がひどい様子。",
 examples:[{jp:"甚だしい誤解です。",romaji:"Hanahadashii gokai desu.",vi:"Đó là một sự hiểu lầm quá mức."}],synonyms:[],compounds:[]},
{kanji:"目覚ましい",hira:"めざましい",kata:"",romaji:"mezamashii",pos:"Tính từ i",level:"N1",topic:"Tính chất",
 vi:["đáng kinh ngạc (tiến bộ)"],en:["remarkable, spectacular"],jp:"驚くほど優れている様子。",
 examples:[{jp:"目覚ましい発展を遂げました。",romaji:"Mezamashii hatten wo togemashita.",vi:"Đã đạt được sự phát triển đáng kinh ngạc."}],synonyms:[],compounds:[]},
{kanji:"円滑",hira:"えんかつ",kata:"",romaji:"enkatsu",pos:"Tính từ na",level:"N1",topic:"Công việc",
 vi:["suôn sẻ, trôi chảy"],en:["smooth"],jp:"物事がスムーズに進む様子。",
 examples:[{jp:"円滑にプロジェクトを進めます。",romaji:"Enkatsu ni purojekuto wo susumemasu.",vi:"Tôi tiến hành dự án một cách suôn sẻ."}],synonyms:[],compounds:[]},
{kanji:"迅速",hira:"じんそく",kata:"",romaji:"jinsoku",pos:"Tính từ na",level:"N1",topic:"Công việc",
 vi:["nhanh chóng"],en:["swift, prompt"],jp:"とても速い様子。",
 examples:[{jp:"迅速に対応します。",romaji:"Jinsoku ni taiou shimasu.",vi:"Chúng tôi sẽ xử lý nhanh chóng."}],synonyms:[],compounds:[]},
{kanji:"慎重",hira:"しんちょう",kata:"",romaji:"shinchou",pos:"Tính từ na",level:"N2",topic:"Tính chất",
 vi:["thận trọng"],en:["cautious, careful"],jp:"注意深く物事を行う様子。",
 examples:[{jp:"慎重に決めてください。",romaji:"Shinchou ni kimete kudasai.",vi:"Hãy quyết định một cách thận trọng."}],synonyms:[],compounds:[]},
{kanji:"大胆",hira:"だいたん",kata:"",romaji:"daitan",pos:"Tính từ na",level:"N2",topic:"Tính chất",
 vi:["táo bạo"],en:["bold"],jp:"思い切って行動する様子。",
 examples:[{jp:"大胆な決断をしました。",romaji:"Daitan na ketsudan wo shimashita.",vi:"Tôi đã đưa ra quyết định táo bạo."}],synonyms:[],compounds:[]},
{kanji:"柔軟",hira:"じゅうなん",kata:"",romaji:"juunan",pos:"Tính từ na",level:"N2",topic:"Tính chất",
 vi:["linh hoạt, mềm dẻo"],en:["flexible"],jp:"状況に応じて変えられる様子。",
 examples:[{jp:"柔軟に対応することが大切です。",romaji:"Juunan ni taiou suru koto ga taisetsu desu.",vi:"Việc ứng phó linh hoạt rất quan trọng."}],synonyms:[],compounds:[]},
{kanji:"効率",hira:"こうりつ",kata:"",romaji:"kouritsu",pos:"Danh từ",level:"N2",topic:"Công việc",
 vi:["hiệu suất"],en:["efficiency"],jp:"少ない労力で多くの結果を出すこと。",
 examples:[{jp:"効率よく仕事をします。",romaji:"Kouritsu yoku shigoto wo shimasu.",vi:"Tôi làm việc một cách hiệu quả."}],synonyms:[],compounds:[]},
{kanji:"促進",hira:"そくしん",kata:"",romaji:"sokushin",pos:"Danh từ / Suru-động từ",level:"N1",topic:"Xã hội",
 vi:["thúc đẩy"],en:["promotion, acceleration"],jp:"物事が早く進むように助けること。",
 examples:[{jp:"経済成長を促進します。",romaji:"Keizai seichou wo sokushin shimasu.",vi:"Thúc đẩy tăng trưởng kinh tế."}],synonyms:[],compounds:[]},
{kanji:"抑制",hira:"よくせい",kata:"",romaji:"yokusei",pos:"Danh từ / Suru-động từ",level:"N1",topic:"Xã hội",
 vi:["kìm hãm, ức chế"],en:["suppression, control"],jp:"勢いを抑えること。",
 examples:[{jp:"感情を抑制します。",romaji:"Kanjou wo yokusei shimasu.",vi:"Tôi kìm nén cảm xúc."}],synonyms:[],compounds:[]},
{kanji:"見通し",hira:"みとおし",kata:"",romaji:"mitooshi",pos:"Danh từ",level:"N1",topic:"Tư duy",
 vi:["triển vọng, dự đoán"],en:["outlook, prospect"],jp:"将来がどうなるかという予測。",
 examples:[{jp:"経済の見通しは明るいです。",romaji:"Keizai no mitooshi wa akarui desu.",vi:"Triển vọng kinh tế khá tươi sáng."}],synonyms:[],compounds:[]},
{kanji:"打開",hira:"だかい",kata:"",romaji:"dakai",pos:"Danh từ / Suru-động từ",level:"N1",topic:"Tư duy",
 vi:["đột phá, tháo gỡ (khó khăn)"],en:["breakthrough"],jp:"難しい状況を解決すること。",
 examples:[{jp:"状況を打開する方法を考えます。",romaji:"Joukyou wo dakai suru houhou wo kangaemasu.",vi:"Tôi suy nghĩ cách tháo gỡ tình hình."}],synonyms:[],compounds:[]},
{kanji:"見極める",hira:"みきわめる",kata:"",romaji:"mikiwameru",pos:"Động từ nhóm 2",level:"N1",topic:"Tư duy",
 vi:["nhận định rõ ràng, xác định chính xác"],en:["to discern, ascertain"],jp:"物事の本質をよく見て判断すること。",
 examples:[{jp:"真実を見極めます。",romaji:"Shinjitsu wo mikiwamemasu.",vi:"Tôi xác định rõ sự thật."}],synonyms:[],compounds:[]},

// ===== Từ vựng chuyên ngành: Công trường xây dựng =====
{kanji:"現場",hira:"げんば",kata:"",romaji:"genba",pos:"Danh từ",level:"Chuyên ngành",topic:"Công trường",
 vi:["hiện trường","công trường"],en:["work site"],jp:"実際に作業を行う場所。",
 examples:[{jp:"今日は現場に行きます。",romaji:"Kyou wa genba ni ikimasu.",vi:"Hôm nay tôi đi công trường."}],synonyms:[],compounds:["建設現場 (công trường xây dựng)"]},
{kanji:"作業",hira:"さぎょう",kata:"",romaji:"sagyou",pos:"Danh từ / Suru-động từ",level:"Chuyên ngành",topic:"Công trường",
 vi:["công việc, thao tác"],en:["work, operation"],jp:"仕事をすること。",
 examples:[{jp:"作業を始めます。",romaji:"Sagyou wo hajimemasu.",vi:"Bắt đầu công việc."}],synonyms:[],compounds:["作業員 (công nhân)","作業服 (đồ bảo hộ)"]},
{kanji:"安全",hira:"あんぜん",kata:"",romaji:"anzen",pos:"Danh từ / Tính từ na",level:"Chuyên ngành",topic:"Công trường",
 vi:["an toàn"],en:["safety"],jp:"危険がないこと。",
 examples:[{jp:"安全第一です。",romaji:"Anzen daiichi desu.",vi:"An toàn là trên hết."}],synonyms:[],compounds:["安全帯 (dây an toàn)","安全靴 (giày bảo hộ)"]},
{kanji:"危険",hira:"きけん",kata:"",romaji:"kiken",pos:"Danh từ / Tính từ na",level:"Chuyên ngành",topic:"Công trường",
 vi:["nguy hiểm"],en:["danger"],jp:"危ないこと。",
 examples:[{jp:"ここは危険です。",romaji:"Koko wa kiken desu.",vi:"Chỗ này nguy hiểm."}],synonyms:[],compounds:["危険物 (vật nguy hiểm)"]},
{kanji:"足場",hira:"あしば",kata:"",romaji:"ashiba",pos:"Danh từ",level:"Chuyên ngành",topic:"Công trường",
 vi:["giàn giáo"],en:["scaffolding"],jp:"高い場所で作業するための台。",
 examples:[{jp:"足場を組み立てます。",romaji:"Ashiba wo kumitatemasu.",vi:"Lắp giàn giáo."}],synonyms:[],compounds:[]},
{kanji:"ヘルメット",hira:"",kata:"ヘルメット",romaji:"herumetto",pos:"Danh từ",level:"Chuyên ngành",topic:"Công trường",
 vi:["mũ bảo hộ"],en:["helmet"],jp:"頭を守るための帽子。",
 examples:[{jp:"ヘルメットをかぶってください。",romaji:"Herumetto wo kabutte kudasai.",vi:"Hãy đội mũ bảo hộ."}],synonyms:[],compounds:[]},
{kanji:"クレーン",hira:"",kata:"クレーン",romaji:"kureen",pos:"Danh từ",level:"Chuyên ngành",topic:"Công trường",
 vi:["cần cẩu"],en:["crane"],jp:"重いものを吊り上げる機械。",
 examples:[{jp:"クレーンで資材を運びます。",romaji:"Kureen de shizai wo hakobimasu.",vi:"Dùng cần cẩu để vận chuyển vật liệu."}],synonyms:[],compounds:[]},
{kanji:"資材",hira:"しざい",kata:"",romaji:"shizai",pos:"Danh từ",level:"Chuyên ngành",topic:"Công trường",
 vi:["vật liệu, vật tư"],en:["materials"],jp:"工事に使う材料。",
 examples:[{jp:"資材を発注します。",romaji:"Shizai wo hacchuu shimasu.",vi:"Đặt hàng vật tư."}],synonyms:[],compounds:[]},
{kanji:"図面",hira:"ずめん",kata:"",romaji:"zumen",pos:"Danh từ",level:"Chuyên ngành",topic:"Công trường",
 vi:["bản vẽ"],en:["blueprint, drawing"],jp:"建物などの設計を表した図。",
 examples:[{jp:"図面を確認してください。",romaji:"Zumen wo kakunin shite kudasai.",vi:"Hãy kiểm tra bản vẽ."}],synonyms:[],compounds:[]},
{kanji:"工事",hira:"こうじ",kata:"",romaji:"kouji",pos:"Danh từ / Suru-động từ",level:"Chuyên ngành",topic:"Công trường",
 vi:["thi công, công trình"],en:["construction work"],jp:"建物や道路などを作る仕事。",
 examples:[{jp:"道路工事をしています。",romaji:"Douro kouji wo shite imasu.",vi:"Đang thi công đường."}],synonyms:[],compounds:["工事現場 (công trường thi công)"]},
{kanji:"組み立てる",hira:"くみたてる",kata:"",romaji:"kumitateru",pos:"Động từ nhóm 2",level:"Chuyên ngành",topic:"Công trường",
 vi:["lắp ráp, dựng lên"],en:["to assemble"],jp:"部品を組んで作ること。",
 examples:[{jp:"機械を組み立てます。",romaji:"Kikai wo kumitatemasu.",vi:"Lắp ráp máy móc."}],synonyms:[],compounds:[]},
{kanji:"点検",hira:"てんけん",kata:"",romaji:"tenken",pos:"Danh từ / Suru-động từ",level:"Chuyên ngành",topic:"Công trường",
 vi:["kiểm tra (định kỳ)"],en:["inspection"],jp:"異常がないか調べること。",
 examples:[{jp:"機械を点検します。",romaji:"Kikai wo tenken shimasu.",vi:"Kiểm tra máy móc."}],synonyms:[],compounds:[]},
{kanji:"指示",hira:"しじ",kata:"",romaji:"shiji",pos:"Danh từ / Suru-động từ",level:"Chuyên ngành",topic:"Công trường",
 vi:["chỉ thị, chỉ đạo"],en:["instruction"],jp:"やるべきことを指図すること。",
 examples:[{jp:"班長の指示に従ってください。",romaji:"Hanchou no shiji ni shitagatte kudasai.",vi:"Hãy làm theo chỉ thị của tổ trưởng."}],synonyms:[],compounds:[]},
{kanji:"班長",hira:"はんちょう",kata:"",romaji:"hanchou",pos:"Danh từ",level:"Chuyên ngành",topic:"Công trường",
 vi:["tổ trưởng"],en:["team leader"],jp:"班のリーダー。",
 examples:[{jp:"班長に報告します。",romaji:"Hanchou ni houkoku shimasu.",vi:"Báo cáo với tổ trưởng."}],synonyms:[],compounds:[]},
{kanji:"報告",hira:"ほうこく",kata:"",romaji:"houkoku",pos:"Danh từ / Suru-động từ",level:"Chuyên ngành",topic:"Công trường",
 vi:["báo cáo"],en:["report"],jp:"結果や状況を伝えること。",
 examples:[{jp:"進捗を報告してください。",romaji:"Shinchoku wo houkoku shite kudasai.",vi:"Hãy báo cáo tiến độ."}],synonyms:[],compounds:["報連相 (báo cáo-liên lạc-bàn bạc)"]},
{kanji:"事故",hira:"じこ",kata:"",romaji:"jiko",pos:"Danh từ",level:"Chuyên ngành",topic:"Công trường",
 vi:["tai nạn, sự cố"],en:["accident"],jp:"予想しない悪い出来事。",
 examples:[{jp:"事故に気をつけてください。",romaji:"Jiko ni ki wo tsukete kudasai.",vi:"Hãy cẩn thận tai nạn."}],synonyms:[],compounds:[]},

// ===== Từ vựng chuyên ngành: Nhà máy / Công xưởng =====
{kanji:"工場",hira:"こうじょう",kata:"",romaji:"koujou",pos:"Danh từ",level:"Chuyên ngành",topic:"Nhà máy",
 vi:["nhà máy, xí nghiệp"],en:["factory"],jp:"物を作る施設。",
 examples:[{jp:"工場で働いています。",romaji:"Koujou de hataraite imasu.",vi:"Tôi làm việc ở nhà máy."}],synonyms:[],compounds:[]},
{kanji:"製造",hira:"せいぞう",kata:"",romaji:"seizou",pos:"Danh từ / Suru-động từ",level:"Chuyên ngành",topic:"Nhà máy",
 vi:["chế tạo, sản xuất"],en:["manufacturing"],jp:"物を作ること。",
 examples:[{jp:"部品を製造します。",romaji:"Buhin wo seizou shimasu.",vi:"Sản xuất linh kiện."}],synonyms:[],compounds:["製造業 (ngành sản xuất)"]},
{kanji:"生産",hira:"せいさん",kata:"",romaji:"seisan",pos:"Danh từ / Suru-động từ",level:"Chuyên ngành",topic:"Nhà máy",
 vi:["sản xuất"],en:["production"],jp:"品物を作り出すこと。",
 examples:[{jp:"生産ラインで働きます。",romaji:"Seisan rain de hatarakimasu.",vi:"Làm việc ở dây chuyền sản xuất."}],synonyms:[],compounds:["生産ライン (dây chuyền sản xuất)"]},
{kanji:"部品",hira:"ぶひん",kata:"",romaji:"buhin",pos:"Danh từ",level:"Chuyên ngành",topic:"Nhà máy",
 vi:["linh kiện, bộ phận"],en:["parts, components"],jp:"機械などを構成する一つ一つのもの。",
 examples:[{jp:"部品を検品します。",romaji:"Buhin wo kenpin shimasu.",vi:"Kiểm tra linh kiện."}],synonyms:[],compounds:[]},
{kanji:"検品",hira:"けんぴん",kata:"",romaji:"kenpin",pos:"Danh từ / Suru-động từ",level:"Chuyên ngành",topic:"Nhà máy",
 vi:["kiểm tra hàng hóa"],en:["product inspection"],jp:"製品に問題がないか調べること。",
 examples:[{jp:"検品して不良品を外します。",romaji:"Kenpin shite furyouhin wo hazushimasu.",vi:"Kiểm tra hàng và loại bỏ sản phẩm lỗi."}],synonyms:[],compounds:[]},
{kanji:"不良品",hira:"ふりょうひん",kata:"",romaji:"furyouhin",pos:"Danh từ",level:"Chuyên ngành",topic:"Nhà máy",
 vi:["sản phẩm lỗi"],en:["defective product"],jp:"品質が悪い製品。",
 examples:[{jp:"不良品を見つけました。",romaji:"Furyouhin wo mitsukemashita.",vi:"Đã tìm thấy sản phẩm lỗi."}],synonyms:[],compounds:[]},
{kanji:"品質",hira:"ひんしつ",kata:"",romaji:"hinshitsu",pos:"Danh từ",level:"Chuyên ngành",topic:"Nhà máy",
 vi:["chất lượng"],en:["quality"],jp:"品物の良さの程度。",
 examples:[{jp:"品質を管理します。",romaji:"Hinshitsu wo kanri shimasu.",vi:"Quản lý chất lượng."}],synonyms:[],compounds:["品質管理 (QC - quản lý chất lượng)"]},
{kanji:"組立",hira:"くみたて",kata:"",romaji:"kumitate",pos:"Danh từ",level:"Chuyên ngành",topic:"Nhà máy",
 vi:["sự lắp ráp"],en:["assembly"],jp:"部品を組み合わせること。",
 examples:[{jp:"組立ラインで作業します。",romaji:"Kumitate rain de sagyou shimasu.",vi:"Làm việc ở dây chuyền lắp ráp."}],synonyms:[],compounds:[]},
{kanji:"梱包",hira:"こんぽう",kata:"",romaji:"konpou",pos:"Danh từ / Suru-động từ",level:"Chuyên ngành",topic:"Nhà máy",
 vi:["đóng gói"],en:["packaging"],jp:"荷物を包んで送る準備をすること。",
 examples:[{jp:"製品を梱包します。",romaji:"Seihin wo konpou shimasu.",vi:"Đóng gói sản phẩm."}],synonyms:[],compounds:[]},
{kanji:"出荷",hira:"しゅっか",kata:"",romaji:"shukka",pos:"Danh từ / Suru-động từ",level:"Chuyên ngành",topic:"Nhà máy",
 vi:["xuất hàng"],en:["shipping (of goods)"],jp:"製品を工場から送り出すこと。",
 examples:[{jp:"明日出荷します。",romaji:"Ashita shukka shimasu.",vi:"Ngày mai xuất hàng."}],synonyms:[],compounds:[]},
{kanji:"在庫",hira:"ざいこ",kata:"",romaji:"zaiko",pos:"Danh từ",level:"Chuyên ngành",topic:"Nhà máy",
 vi:["hàng tồn kho"],en:["stock, inventory"],jp:"倉庫にある品物。",
 examples:[{jp:"在庫を確認します。",romaji:"Zaiko wo kakunin shimasu.",vi:"Kiểm tra hàng tồn kho."}],synonyms:[],compounds:[]},
{kanji:"倉庫",hira:"そうこ",kata:"",romaji:"souko",pos:"Danh từ",level:"Chuyên ngành",topic:"Nhà máy",
 vi:["kho hàng"],en:["warehouse"],jp:"物をしまっておく建物。",
 examples:[{jp:"倉庫に運びます。",romaji:"Souko ni hakobimasu.",vi:"Vận chuyển đến kho."}],synonyms:[],compounds:[]},
{kanji:"交代",hira:"こうたい",kata:"",romaji:"koutai",pos:"Danh từ / Suru-động từ",level:"Chuyên ngành",topic:"Nhà máy",
 vi:["thay ca"],en:["shift change"],jp:"順番に代わること。",
 examples:[{jp:"三時に交代します。",romaji:"Sanji ni koutai shimasu.",vi:"3 giờ thay ca."}],synonyms:[],compounds:["交代制 (chế độ ca kíp)"]},
{kanji:"残業",hira:"ざんぎょう",kata:"",romaji:"zangyou",pos:"Danh từ / Suru-động từ",level:"Chuyên ngành",topic:"Nhà máy",
 vi:["làm thêm giờ (tăng ca)"],en:["overtime work"],jp:"決められた時間の後も働くこと。",
 examples:[{jp:"今日は残業します。",romaji:"Kyou wa zangyou shimasu.",vi:"Hôm nay tôi tăng ca."}],synonyms:[],compounds:[]},

// ===== Từ vựng chuyên ngành: Cơ khí =====
{kanji:"機械",hira:"きかい",kata:"",romaji:"kikai",pos:"Danh từ",level:"Chuyên ngành",topic:"Cơ khí",
 vi:["máy móc"],en:["machine"],jp:"動力で動く道具。",
 examples:[{jp:"機械を操作します。",romaji:"Kikai wo sousa shimasu.",vi:"Vận hành máy móc."}],synonyms:[],compounds:[]},
{kanji:"操作",hira:"そうさ",kata:"",romaji:"sousa",pos:"Danh từ / Suru-động từ",level:"Chuyên ngành",topic:"Cơ khí",
 vi:["vận hành, thao tác"],en:["operation"],jp:"機械を動かすこと。",
 examples:[{jp:"操作方法を教えてください。",romaji:"Sousa houhou wo oshiete kudasai.",vi:"Hãy chỉ tôi cách vận hành."}],synonyms:[],compounds:[]},
{kanji:"部材",hira:"ぶざい",kata:"",romaji:"buzai",pos:"Danh từ",level:"Chuyên ngành",topic:"Cơ khí",
 vi:["cấu kiện, vật liệu cấu thành"],en:["component material"],jp:"物を構成する材料。",
 examples:[{jp:"部材を溶接します。",romaji:"Buzai wo yousetsu shimasu.",vi:"Hàn các cấu kiện."}],synonyms:[],compounds:[]},
{kanji:"溶接",hira:"ようせつ",kata:"",romaji:"yousetsu",pos:"Danh từ / Suru-động từ",level:"Chuyên ngành",topic:"Cơ khí",
 vi:["hàn (kim loại)"],en:["welding"],jp:"金属を熱でつなぐこと。",
 examples:[{jp:"溶接の資格を持っています。",romaji:"Yousetsu no shikaku wo motte imasu.",vi:"Tôi có chứng chỉ hàn."}],synonyms:[],compounds:[]},
{kanji:"切断",hira:"せつだん",kata:"",romaji:"setsudan",pos:"Danh từ / Suru-động từ",level:"Chuyên ngành",topic:"Cơ khí",
 vi:["cắt (vật liệu)"],en:["cutting"],jp:"物を切り離すこと。",
 examples:[{jp:"鉄板を切断します。",romaji:"Teppan wo setsudan shimasu.",vi:"Cắt tấm sắt."}],synonyms:[],compounds:[]},
{kanji:"研磨",hira:"けんま",kata:"",romaji:"kenma",pos:"Danh từ / Suru-động từ",level:"Chuyên ngành",topic:"Cơ khí",
 vi:["mài, đánh bóng"],en:["grinding, polishing"],jp:"表面を磨いて滑らかにすること。",
 examples:[{jp:"表面を研磨します。",romaji:"Hyoumen wo kenma shimasu.",vi:"Mài bề mặt."}],synonyms:[],compounds:[]},
{kanji:"塗装",hira:"とそう",kata:"",romaji:"tosou",pos:"Danh từ / Suru-động từ",level:"Chuyên ngành",topic:"Cơ khí",
 vi:["sơn phủ"],en:["painting, coating"],jp:"表面に塗料をぬること。",
 examples:[{jp:"部品を塗装します。",romaji:"Buhin wo tosou shimasu.",vi:"Sơn linh kiện."}],synonyms:[],compounds:[]},
{kanji:"歯車",hira:"はぐるま",kata:"",romaji:"haguruma",pos:"Danh từ",level:"Chuyên ngành",topic:"Cơ khí",
 vi:["bánh răng"],en:["gear"],jp:"回転を伝える機械部品。",
 examples:[{jp:"歯車が壊れました。",romaji:"Haguruma ga kowaremashita.",vi:"Bánh răng bị hỏng."}],synonyms:[],compounds:[]},
{kanji:"油圧",hira:"ゆあつ",kata:"",romaji:"yuatsu",pos:"Danh từ",level:"Chuyên ngành",topic:"Cơ khí",
 vi:["thủy lực"],en:["hydraulic pressure"],jp:"油の圧力を使う仕組み。",
 examples:[{jp:"油圧システムを点検します。",romaji:"Yuatsu shisutemu wo tenken shimasu.",vi:"Kiểm tra hệ thống thủy lực."}],synonyms:[],compounds:[]},
{kanji:"故障",hira:"こしょう",kata:"",romaji:"koshou",pos:"Danh từ / Suru-động từ",level:"Chuyên ngành",topic:"Cơ khí",
 vi:["hỏng hóc (máy móc)"],en:["breakdown, malfunction"],jp:"機械が動かなくなること。",
 examples:[{jp:"機械が故障しました。",romaji:"Kikai ga koshou shimashita.",vi:"Máy móc bị hỏng."}],synonyms:[],compounds:[]},
{kanji:"修理",hira:"しゅうり",kata:"",romaji:"shuuri",pos:"Danh từ / Suru-động từ",level:"Chuyên ngành",topic:"Cơ khí",
 vi:["sửa chữa"],en:["repair"],jp:"壊れた物を直すこと。",
 examples:[{jp:"機械を修理します。",romaji:"Kikai wo shuuri shimasu.",vi:"Sửa chữa máy móc."}],synonyms:[],compounds:[]},
{kanji:"工具",hira:"こうぐ",kata:"",romaji:"kougu",pos:"Danh từ",level:"Chuyên ngành",topic:"Cơ khí",
 vi:["dụng cụ, đồ nghề"],en:["tool"],jp:"作業に使う道具。",
 examples:[{jp:"工具を使います。",romaji:"Kougu wo tsukaimasu.",vi:"Sử dụng dụng cụ."}],synonyms:[],compounds:[]},

// ===== Từ vựng chuyên ngành: Kiến trúc / Xây dựng =====
{kanji:"設計",hira:"せっけい",kata:"",romaji:"sekkei",pos:"Danh từ / Suru-động từ",level:"Chuyên ngành",topic:"Kiến trúc",
 vi:["thiết kế"],en:["design"],jp:"建物などの計画を立てること。",
 examples:[{jp:"建物を設計します。",romaji:"Tatemono wo sekkei shimasu.",vi:"Thiết kế công trình."}],synonyms:[],compounds:[]},
{kanji:"基礎",hira:"きそ",kata:"",romaji:"kiso",pos:"Danh từ",level:"Chuyên ngành",topic:"Kiến trúc",
 vi:["nền móng"],en:["foundation"],jp:"建物を支える土台。",
 examples:[{jp:"基礎工事をします。",romaji:"Kiso kouji wo shimasu.",vi:"Thi công nền móng."}],synonyms:[],compounds:[]},
{kanji:"鉄筋",hira:"てっきん",kata:"",romaji:"tekkin",pos:"Danh từ",level:"Chuyên ngành",topic:"Kiến trúc",
 vi:["cốt thép"],en:["reinforcing steel, rebar"],jp:"コンクリートを補強する鉄の棒。",
 examples:[{jp:"鉄筋を組みます。",romaji:"Tekkin wo kumimasu.",vi:"Buộc cốt thép."}],synonyms:[],compounds:["鉄筋コンクリート (bê tông cốt thép)"]},
{kanji:"コンクリート",hira:"",kata:"コンクリート",romaji:"konkuriito",pos:"Danh từ",level:"Chuyên ngành",topic:"Kiến trúc",
 vi:["bê tông"],en:["concrete"],jp:"セメントと砂などを混ぜた建築材料。",
 examples:[{jp:"コンクリートを流し込みます。",romaji:"Konkuriito wo nagashikomimasu.",vi:"Đổ bê tông."}],synonyms:[],compounds:[]},
{kanji:"壁",hira:"かべ",kata:"",romaji:"kabe",pos:"Danh từ",level:"Chuyên ngành",topic:"Kiến trúc",
 vi:["tường"],en:["wall"],jp:"部屋や建物を区切るもの。",
 examples:[{jp:"壁を塗ります。",romaji:"Kabe wo nurimasu.",vi:"Sơn tường."}],synonyms:[],compounds:[]},
{kanji:"屋根",hira:"やね",kata:"",romaji:"yane",pos:"Danh từ",level:"Chuyên ngành",topic:"Kiến trúc",
 vi:["mái nhà"],en:["roof"],jp:"建物の一番上をおおうもの。",
 examples:[{jp:"屋根を修理します。",romaji:"Yane wo shuuri shimasu.",vi:"Sửa mái nhà."}],synonyms:[],compounds:[]},
{kanji:"配管",hira:"はいかん",kata:"",romaji:"haikan",pos:"Danh từ / Suru-động từ",level:"Chuyên ngành",topic:"Kiến trúc",
 vi:["lắp đặt đường ống"],en:["piping"],jp:"パイプを取り付けること。",
 examples:[{jp:"配管工事をします。",romaji:"Haikan kouji wo shimasu.",vi:"Thi công lắp đặt đường ống."}],synonyms:[],compounds:[]},
{kanji:"配線",hira:"はいせん",kata:"",romaji:"haisen",pos:"Danh từ / Suru-động từ",level:"Chuyên ngành",topic:"Kiến trúc",
 vi:["đi dây điện"],en:["electrical wiring"],jp:"電線を取り付けること。",
 examples:[{jp:"配線工事をします。",romaji:"Haisen kouji wo shimasu.",vi:"Thi công đi dây điện."}],synonyms:[],compounds:[]},
{kanji:"建築",hira:"けんちく",kata:"",romaji:"kenchiku",pos:"Danh từ / Suru-động từ",level:"Chuyên ngành",topic:"Kiến trúc",
 vi:["kiến trúc, xây dựng"],en:["architecture, construction"],jp:"建物を建てること。",
 examples:[{jp:"建築の仕事をしています。",romaji:"Kenchiku no shigoto wo shite imasu.",vi:"Tôi làm nghề xây dựng."}],synonyms:[],compounds:["建築士 (kiến trúc sư)"]},
{kanji:"施工",hira:"せこう",kata:"",romaji:"sekou",pos:"Danh từ / Suru-động từ",level:"Chuyên ngành",topic:"Kiến trúc",
 vi:["thi công"],en:["construction execution"],jp:"工事を実際に行うこと。",
 examples:[{jp:"施工管理をします。",romaji:"Sekou kanri wo shimasu.",vi:"Quản lý thi công."}],synonyms:[],compounds:[]},
{kanji:"寸法",hira:"すんぽう",kata:"",romaji:"sunpou",pos:"Danh từ",level:"Chuyên ngành",topic:"Kiến trúc",
 vi:["kích thước"],en:["dimensions, measurements"],jp:"物の大きさ、長さ。",
 examples:[{jp:"寸法を測ります。",romaji:"Sunpou wo hakarimasu.",vi:"Đo kích thước."}],synonyms:[],compounds:[]},
{kanji:"測る",hira:"はかる",kata:"",romaji:"hakaru",pos:"Động từ nhóm 1",level:"Chuyên ngành",topic:"Kiến trúc",
 vi:["đo (kích thước)"],en:["to measure"],jp:"長さや重さを調べること。",
 examples:[{jp:"長さを測ります。",romaji:"Nagasa wo hakarimasu.",vi:"Đo chiều dài."}],synonyms:[],compounds:[]},
];

// Remove placeholder entry
const VOCAB_CLEAN = VOCAB.filter(v => v.kanji !== "electron_placeholder");

const KANJI = [
{char:"日",onyomi:["ニチ","ジツ"],kunyomi:["ひ","-び","-か"],meaning:"ngày, mặt trời",strokes:4,level:"N5",radical:"日",
 compounds:[{word:"日本",reading:"にほん",meaning:"Nhật Bản"},{word:"今日",reading:"きょう",meaning:"hôm nay"}]},
{char:"本",onyomi:["ホン"],kunyomi:["もと"],meaning:"sách, gốc, bản",strokes:5,level:"N5",radical:"木",
 compounds:[{word:"本当",reading:"ほんとう",meaning:"thật sự"},{word:"日本",reading:"にほん",meaning:"Nhật Bản"}]},
{char:"人",onyomi:["ジン","ニン"],kunyomi:["ひと"],meaning:"người",strokes:2,level:"N5",radical:"人",
 compounds:[{word:"日本人",reading:"にほんじん",meaning:"người Nhật"},{word:"外国人",reading:"がいこくじん",meaning:"người nước ngoài"}]},
{char:"学",onyomi:["ガク"],kunyomi:["まな-ぶ"],meaning:"học",strokes:8,level:"N5",radical:"子",
 compounds:[{word:"学校",reading:"がっこう",meaning:"trường học"},{word:"学生",reading:"がくせい",meaning:"học sinh"}]},
{char:"校",onyomi:["コウ"],kunyomi:[],meaning:"trường học",strokes:10,level:"N5",radical:"木",
 compounds:[{word:"学校",reading:"がっこう",meaning:"trường học"},{word:"高校",reading:"こうこう",meaning:"trung học phổ thông"}]},
{char:"食",onyomi:["ショク"],kunyomi:["た-べる","く-う"],meaning:"ăn, thức ăn",strokes:9,level:"N5",radical:"食",
 compounds:[{word:"食べる",reading:"たべる",meaning:"ăn"},{word:"食事",reading:"しょくじ",meaning:"bữa ăn"}]},
{char:"飲",onyomi:["イン"],kunyomi:["の-む"],meaning:"uống",strokes:12,level:"N5",radical:"食",
 compounds:[{word:"飲み物",reading:"のみもの",meaning:"đồ uống"}]},
{char:"水",onyomi:["スイ"],kunyomi:["みず"],meaning:"nước",strokes:4,level:"N5",radical:"水",
 compounds:[{word:"水曜日",reading:"すいようび",meaning:"thứ Tư"}]},
{char:"火",onyomi:["カ"],kunyomi:["ひ"],meaning:"lửa",strokes:4,level:"N5",radical:"火",
 compounds:[{word:"火曜日",reading:"かようび",meaning:"thứ Ba"}]},
{char:"木",onyomi:["モク","ボク"],kunyomi:["き"],meaning:"cây, gỗ",strokes:4,level:"N5",radical:"木",
 compounds:[{word:"木曜日",reading:"もくようび",meaning:"thứ Năm"}]},
{char:"金",onyomi:["キン"],kunyomi:["かね"],meaning:"vàng, tiền",strokes:8,level:"N5",radical:"金",
 compounds:[{word:"金曜日",reading:"きんようび",meaning:"thứ Sáu"},{word:"お金",reading:"おかね",meaning:"tiền"}]},
{char:"土",onyomi:["ド","ト"],kunyomi:["つち"],meaning:"đất",strokes:3,level:"N5",radical:"土",
 compounds:[{word:"土曜日",reading:"どようび",meaning:"thứ Bảy"}]},
{char:"月",onyomi:["ゲツ","ガツ"],kunyomi:["つき"],meaning:"tháng, mặt trăng",strokes:4,level:"N5",radical:"月",
 compounds:[{word:"月曜日",reading:"げつようび",meaning:"thứ Hai"},{word:"来月",reading:"らいげつ",meaning:"tháng sau"}]},
{char:"time_placeholder",onyomi:[],kunyomi:[],meaning:"",strokes:0,level:"",radical:"",compounds:[]},
{char:"時",onyomi:["ジ"],kunyomi:["とき"],meaning:"giờ, thời gian",strokes:10,level:"N5",radical:"日",
 compounds:[{word:"時間",reading:"じかん",meaning:"thời gian"},{word:"何時",reading:"なんじ",meaning:"mấy giờ"}]},
{char:"間",onyomi:["カン","ケン"],kunyomi:["あいだ"],meaning:"khoảng, giữa",strokes:12,level:"N5",radical:"門",
 compounds:[{word:"時間",reading:"じかん",meaning:"thời gian"},{word:"人間",reading:"にんげん",meaning:"con người"}]},
{char:"友",onyomi:["ユウ"],kunyomi:["とも"],meaning:"bạn",strokes:4,level:"N5",radical:"又",
 compounds:[{word:"友達",reading:"ともだち",meaning:"bạn bè"}]},
{char:"先",onyomi:["セン"],kunyomi:["さき"],meaning:"trước, sớm",strokes:6,level:"N5",radical:"儿",
 compounds:[{word:"先生",reading:"せんせい",meaning:"giáo viên"},{word:"先週",reading:"せんしゅう",meaning:"tuần trước"}]},
{char:"生",onyomi:["セイ","ショウ"],kunyomi:["い-きる","う-まれる"],meaning:"sinh, sống",strokes:5,level:"N5",radical:"生",
 compounds:[{word:"先生",reading:"せんせい",meaning:"giáo viên"},{word:"学生",reading:"がくせい",meaning:"học sinh"}]},
{char:"働",onyomi:["ドウ"],kunyomi:["はたら-く"],meaning:"làm việc",strokes:13,level:"N4",radical:"人",
 compounds:[{word:"働く",reading:"はたらく",meaning:"làm việc"}]},
{char:"仕",onyomi:["シ"],kunyomi:["つか-える"],meaning:"phụng sự, làm",strokes:5,level:"N4",radical:"人",
 compounds:[{word:"仕事",reading:"しごと",meaning:"công việc"}]},
{char:"事",onyomi:["ジ"],kunyomi:["こと"],meaning:"việc, sự việc",strokes:8,level:"N4",radical:"亅",
 compounds:[{word:"仕事",reading:"しごと",meaning:"công việc"},{word:"大事",reading:"だいじ",meaning:"quan trọng"}]},
{char:"難",onyomi:["ナン"],kunyomi:["むずか-しい"],meaning:"khó khăn",strokes:18,level:"N4",radical:"隹",
 compounds:[{word:"難しい",reading:"むずかしい",meaning:"khó"}]},
{char:"経",onyomi:["ケイ"],kunyomi:["へ-る"],meaning:"trải qua, kinh",strokes:11,level:"N3",radical:"糸",
 compounds:[{word:"経験",reading:"けいけん",meaning:"kinh nghiệm"},{word:"経済",reading:"けいざい",meaning:"kinh tế"}]},
{char:"験",onyomi:["ケン"],kunyomi:[],meaning:"thử nghiệm, hiệu quả",strokes:18,level:"N3",radical:"馬",
 compounds:[{word:"経験",reading:"けいけん",meaning:"kinh nghiệm"},{word:"試験",reading:"しけん",meaning:"kỳ thi"}]},
{char:"影",onyomi:["エイ"],kunyomi:["かげ"],meaning:"bóng, hình bóng",strokes:15,level:"N3",radical:"彡",
 compounds:[{word:"影響",reading:"えいきょう",meaning:"ảnh hưởng"}]},
{char:"響",onyomi:["キョウ"],kunyomi:["ひび-く"],meaning:"vang, âm hưởng",strokes:20,level:"N2",radical:"音",
 compounds:[{word:"影響",reading:"えいきょう",meaning:"ảnh hưởng"}]},
{char:"環",onyomi:["カン"],kunyomi:["わ"],meaning:"vòng, chu kỳ",strokes:17,level:"N3",radical:"玉",
 compounds:[{word:"環境",reading:"かんきょう",meaning:"môi trường"}]},
{char:"境",onyomi:["キョウ"],kunyomi:["さかい"],meaning:"biên giới, ranh giới",strokes:14,level:"N3",radical:"土",
 compounds:[{word:"環境",reading:"かんきょう",meaning:"môi trường"},{word:"国境",reading:"こっきょう",meaning:"biên giới quốc gia"}]},
{char:"解",onyomi:["カイ","ゲ"],kunyomi:["と-く"],meaning:"giải, hiểu",strokes:13,level:"N2",radical:"角",
 compounds:[{word:"解決",reading:"かいけつ",meaning:"giải quyết"},{word:"理解",reading:"りかい",meaning:"lý giải, hiểu"}]},
{char:"決",onyomi:["ケツ"],kunyomi:["き-める"],meaning:"quyết định",strokes:7,level:"N3",radical:"水",
 compounds:[{word:"解決",reading:"かいけつ",meaning:"giải quyết"},{word:"決める",reading:"きめる",meaning:"quyết định"}]},
{char:"矛",onyomi:["ム"],kunyomi:["ほこ"],meaning:"cây giáo (vũ khí)",strokes:5,level:"N1",radical:"矛",
 compounds:[{word:"矛盾",reading:"むじゅん",meaning:"mâu thuẫn"}]},
{char:"盾",onyomi:["ジュン"],kunyomi:["たて"],meaning:"cái khiên",strokes:9,level:"N1",radical:"目",
 compounds:[{word:"矛盾",reading:"むじゅん",meaning:"mâu thuẫn"}]},
{char:"優",onyomi:["ユウ"],kunyomi:["やさ-しい"],meaning:"ưu tú, dịu dàng",strokes:17,level:"N2",radical:"人",
 compounds:[{word:"優先",reading:"ゆうせん",meaning:"ưu tiên"},{word:"優しい",reading:"やさしい",meaning:"hiền, dịu dàng"}]},
{char:"先",onyomi:["セン"],kunyomi:["さき"],meaning:"trước",strokes:6,level:"N5",radical:"儿",compounds:[]},
{char:"曖",onyomi:["アイ"],kunyomi:[],meaning:"mờ tối, không rõ",strokes:17,level:"N1",radical:"日",
 compounds:[{word:"曖昧",reading:"あいまい",meaning:"mơ hồ"}]},
{char:"昧",onyomi:["マイ"],kunyomi:[],meaning:"tối tăm, u mê",strokes:9,level:"N1",radical:"日",
 compounds:[{word:"曖昧",reading:"あいまい",meaning:"mơ hồ"}]},
{char:"配",onyomi:["ハイ"],kunyomi:["くば-る"],meaning:"phân phối, quan tâm",strokes:10,level:"N2",radical:"酉",
 compounds:[{word:"配慮",reading:"はいりょ",meaning:"quan tâm chu đáo"},{word:"心配",reading:"しんぱい",meaning:"lo lắng"}]},
{char:"慮",onyomi:["リョ"],kunyomi:[],meaning:"suy nghĩ, cân nhắc",strokes:15,level:"N1",radical:"心",
 compounds:[{word:"配慮",reading:"はいりょ",meaning:"quan tâm chu đáo"}]},
{char:"信",onyomi:["シン"],kunyomi:[],meaning:"tin tưởng",strokes:9,level:"N4",radical:"人",
 compounds:[{word:"信頼",reading:"しんらい",meaning:"tin tưởng"},{word:"自信",reading:"じしん",meaning:"tự tin"}]},
{char:"頼",onyomi:["ライ"],kunyomi:["たの-む"],meaning:"nhờ vả, dựa vào",strokes:16,level:"N2",radical:"頁",
 compounds:[{word:"信頼",reading:"しんらい",meaning:"tin tưởng"}]},
{char:"注",onyomi:["チュウ"],kunyomi:["そそ-ぐ"],meaning:"rót, chú ý",strokes:8,level:"N4",radical:"水",
 compounds:[{word:"注意",reading:"ちゅうい",meaning:"chú ý"}]},
{char:"意",onyomi:["イ"],kunyomi:[],meaning:"ý nghĩa, ý định",strokes:13,level:"N4",radical:"心",
 compounds:[{word:"注意",reading:"ちゅうい",meaning:"chú ý"},{word:"意味",reading:"いみ",meaning:"ý nghĩa"}]},

// ===== Bổ sung thêm Kanji (mở rộng N4→N1) =====
{char:"改",onyomi:["カイ"],kunyomi:["あらた-める"],meaning:"sửa đổi, cải cách",strokes:7,level:"N3",radical:"攴",
 compounds:[{word:"改善",reading:"かいぜん",meaning:"cải thiện"}]},
{char:"善",onyomi:["ゼン"],kunyomi:["よ-い"],meaning:"tốt, thiện",strokes:12,level:"N2",radical:"口",
 compounds:[{word:"改善",reading:"かいぜん",meaning:"cải thiện"}]},
{char:"普",onyomi:["フ"],kunyomi:[],meaning:"phổ biến, rộng khắp",strokes:12,level:"N2",radical:"日",
 compounds:[{word:"普及",reading:"ふきゅう",meaning:"phổ biến rộng rãi"}]},
{char:"及",onyomi:["キュウ"],kunyomi:["およ-ぶ"],meaning:"đạt đến, kịp",strokes:3,level:"N2",radical:"又",
 compounds:[{word:"普及",reading:"ふきゅう",meaning:"phổ biến rộng rãi"}]},
{char:"依",onyomi:["イ"],kunyomi:[],meaning:"dựa vào",strokes:8,level:"N2",radical:"人",
 compounds:[{word:"依然",reading:"いぜん",meaning:"vẫn như cũ"}]},
{char:"重",onyomi:["ジュウ","チョウ"],kunyomi:["おも-い","かさ-ねる"],meaning:"nặng, quan trọng",strokes:9,level:"N4",radical:"里",
 compounds:[{word:"重視",reading:"じゅうし",meaning:"coi trọng"},{word:"重要",reading:"じゅうよう",meaning:"quan trọng"}]},
{char:"模",onyomi:["モ"],kunyomi:[],meaning:"khuôn mẫu, mô phỏng",strokes:14,level:"N1",radical:"木",
 compounds:[{word:"模索",reading:"もさく",meaning:"dò dẫm tìm kiếm"}]},
{char:"索",onyomi:["サク"],kunyomi:[],meaning:"tìm kiếm, dây thừng",strokes:10,level:"N1",radical:"糸",
 compounds:[{word:"模索",reading:"もさく",meaning:"dò dẫm tìm kiếm"},{word:"検索",reading:"けんさく",meaning:"tra cứu, tìm kiếm"}]},
{char:"雇",onyomi:["コ"],kunyomi:["やと-う"],meaning:"thuê, tuyển dụng",strokes:12,level:"N1",radical:"隹",
 compounds:[{word:"雇用",reading:"こよう",meaning:"tuyển dụng"}]},
{char:"転",onyomi:["テン"],kunyomi:["ころ-がる"],meaning:"xoay, chuyển",strokes:11,level:"N3",radical:"車",
 compounds:[{word:"転職",reading:"てんしょく",meaning:"chuyển việc"},{word:"運転",reading:"うんてん",meaning:"lái xe"}]},
{char:"刻",onyomi:["コク"],kunyomi:["きざ-む"],meaning:"khắc, thời khắc",strokes:8,level:"N2",radical:"刀",
 compounds:[{word:"深刻",reading:"しんこく",meaning:"nghiêm trọng"}]},
{char:"暖",onyomi:["ダン"],kunyomi:["あたた-かい"],meaning:"ấm áp",strokes:13,level:"N3",radical:"日",
 compounds:[{word:"温暖化",reading:"おんだんか",meaning:"hiện tượng ấm lên"}]},
{char:"異",onyomi:["イ"],kunyomi:["こと-なる"],meaning:"khác lạ, dị thường",strokes:11,level:"N3",radical:"田",
 compounds:[{word:"異常",reading:"いじょう",meaning:"bất thường"}]},
{char:"共",onyomi:["キョウ"],kunyomi:["とも"],meaning:"cùng nhau",strokes:6,level:"N3",radical:"八",
 compounds:[{word:"公共",reading:"こうきょう",meaning:"công cộng"},{word:"共通",reading:"きょうつう",meaning:"chung"}]},
{char:"疑",onyomi:["ギ"],kunyomi:["うたが-う"],meaning:"nghi ngờ",strokes:14,level:"N3",radical:"疋",
 compounds:[{word:"疑う",reading:"うたがう",meaning:"nghi ngờ"},{word:"質疑",reading:"しつぎ",meaning:"chất vấn"}]},
{char:"実",onyomi:["ジツ"],kunyomi:["み","じつ-に"],meaning:"thực tế, quả thật",strokes:8,level:"N3",radical:"宀",
 compounds:[{word:"実現",reading:"じつげん",meaning:"hiện thực hóa"},{word:"事実",reading:"じじつ",meaning:"sự thật"}]},
{char:"否",onyomi:["ヒ"],kunyomi:["いな"],meaning:"phủ định",strokes:7,level:"N2",radical:"口",
 compounds:[{word:"否定",reading:"ひてい",meaning:"phủ định"}]},
{char:"肯",onyomi:["コウ"],kunyomi:[],meaning:"đồng ý, chấp thuận",strokes:8,level:"N2",radical:"月",
 compounds:[{word:"肯定",reading:"こうてい",meaning:"khẳng định"}]},
{char:"抽",onyomi:["チュウ"],kunyomi:[],meaning:"rút ra, trừu tượng",strokes:8,level:"N1",radical:"手",
 compounds:[{word:"抽象的",reading:"ちゅうしょうてき",meaning:"trừu tượng"}]},
{char:"象",onyomi:["ショウ","ゾウ"],kunyomi:[],meaning:"hình tượng, con voi",strokes:12,level:"N2",radical:"豕",
 compounds:[{word:"抽象的",reading:"ちゅうしょうてき",meaning:"trừu tượng"},{word:"印象",reading:"いんしょう",meaning:"ấn tượng"}]},
{char:"具",onyomi:["グ"],kunyomi:[],meaning:"cụ thể, dụng cụ",strokes:8,level:"N2",radical:"八",
 compounds:[{word:"具体的",reading:"ぐたいてき",meaning:"cụ thể"},{word:"道具",reading:"どうぐ",meaning:"công cụ"}]},
{char:"率",onyomi:["リツ","ソツ"],kunyomi:["ひき-いる"],meaning:"tỉ lệ, dẫn dắt",strokes:11,level:"N2",radical:"玄",
 compounds:[{word:"率直",reading:"そっちょく",meaning:"thẳng thắn"},{word:"効率",reading:"こうりつ",meaning:"hiệu suất"}]},
{char:"謙",onyomi:["ケン"],kunyomi:[],meaning:"khiêm tốn",strokes:17,level:"N1",radical:"言",
 compounds:[{word:"謙虚",reading:"けんきょ",meaning:"khiêm tốn"}]},
{char:"虚",onyomi:["キョ"],kunyomi:[],meaning:"trống rỗng, hư",strokes:11,level:"N1",radical:"虍",
 compounds:[{word:"謙虚",reading:"けんきょ",meaning:"khiêm tốn"}]},
{char:"贅",onyomi:["ゼイ"],kunyomi:[],meaning:"dư thừa, xa xỉ",strokes:18,level:"N1",radical:"貝",
 compounds:[{word:"贅沢",reading:"ぜいたく",meaning:"xa xỉ"}]},
{char:"沢",onyomi:["タク"],kunyomi:["さわ"],meaning:"đầm lầy, nhiều",strokes:7,level:"N2",radical:"水",
 compounds:[{word:"贅沢",reading:"ぜいたく",meaning:"xa xỉ"}]},
{char:"倹",onyomi:["ケン"],kunyomi:[],meaning:"tiết kiệm",strokes:10,level:"N1",radical:"人",
 compounds:[{word:"倹約",reading:"けんやく",meaning:"tiết kiệm"}]},
{char:"貯",onyomi:["チョ"],kunyomi:["た-める"],meaning:"tích trữ",strokes:12,level:"N3",radical:"貝",
 compounds:[{word:"貯金",reading:"ちょきん",meaning:"tiền tiết kiệm"}]},
{char:"税",onyomi:["ゼイ"],kunyomi:[],meaning:"thuế",strokes:12,level:"N3",radical:"禾",
 compounds:[{word:"税金",reading:"ぜいきん",meaning:"thuế"}]},
{char:"景",onyomi:["ケイ"],kunyomi:[],meaning:"cảnh, tình hình",strokes:12,level:"N2",radical:"日",
 compounds:[{word:"景気",reading:"けいき",meaning:"tình hình kinh tế"},{word:"景色",reading:"けしき",meaning:"phong cảnh"}]},
{char:"況",onyomi:["キョウ"],kunyomi:[],meaning:"tình huống",strokes:8,level:"N2",radical:"水",
 compounds:[{word:"不況",reading:"ふきょう",meaning:"suy thoái kinh tế"},{word:"状況",reading:"じょうきょう",meaning:"tình hình"}]},
{char:"就",onyomi:["シュウ"],kunyomi:["つ-く"],meaning:"nhận (chức vụ)",strokes:12,level:"N3",radical:"尢",
 compounds:[{word:"就職",reading:"しゅうしょく",meaning:"xin việc"}]},
{char:"退",onyomi:["タイ"],kunyomi:["しりぞ-く"],meaning:"lui, rút lui",strokes:9,level:"N2",radical:"辵",
 compounds:[{word:"退職",reading:"たいしょく",meaning:"nghỉ hưu/nghỉ việc"}]},
{char:"昇",onyomi:["ショウ"],kunyomi:["のぼ-る"],meaning:"thăng, lên",strokes:8,level:"N1",radical:"日",
 compounds:[{word:"昇進",reading:"しょうしん",meaning:"thăng chức"}]},
{char:"責",onyomi:["セキ"],kunyomi:["せ-める"],meaning:"trách nhiệm",strokes:11,level:"N3",radical:"貝",
 compounds:[{word:"責任",reading:"せきにん",meaning:"trách nhiệm"}]},
{char:"義",onyomi:["ギ"],kunyomi:[],meaning:"nghĩa vụ, chính nghĩa",strokes:13,level:"N2",radical:"羊",
 compounds:[{word:"義務",reading:"ぎむ",meaning:"nghĩa vụ"},{word:"意義",reading:"いぎ",meaning:"ý nghĩa"}]},
{char:"権",onyomi:["ケン"],kunyomi:[],meaning:"quyền lực",strokes:15,level:"N2",radical:"木",
 compounds:[{word:"権利",reading:"けんり",meaning:"quyền lợi"}]},
{char:"律",onyomi:["リツ"],kunyomi:[],meaning:"luật lệ",strokes:9,level:"N3",radical:"彳",
 compounds:[{word:"法律",reading:"ほうりつ",meaning:"pháp luật"}]},
{char:"違",onyomi:["イ"],kunyomi:["ちが-う"],meaning:"khác, vi phạm",strokes:13,level:"N3",radical:"辵",
 compounds:[{word:"違反",reading:"いはん",meaning:"vi phạm"},{word:"間違い",reading:"まちがい",meaning:"sai lầm"}]},
{char:"討",onyomi:["トウ"],kunyomi:[],meaning:"bàn luận, thảo phạt",strokes:10,level:"N2",radical:"言",
 compounds:[{word:"検討",reading:"けんとう",meaning:"xem xét"}]},
{char:"案",onyomi:["アン"],kunyomi:[],meaning:"phương án, đề án",strokes:10,level:"N3",radical:"木",
 compounds:[{word:"提案",reading:"ていあん",meaning:"đề xuất"},{word:"案内",reading:"あんない",meaning:"hướng dẫn"}]},
{char:"承",onyomi:["ショウ"],kunyomi:["うけたまわ-る"],meaning:"nhận, chấp thuận",strokes:8,level:"N1",radical:"手",
 compounds:[{word:"承認",reading:"しょうにん",meaning:"phê duyệt"}]},
{char:"妥",onyomi:["ダ"],kunyomi:[],meaning:"thỏa đáng",strokes:7,level:"N1",radical:"女",
 compounds:[{word:"妥協",reading:"だきょう",meaning:"thỏa hiệp"}]},
{char:"協",onyomi:["キョウ"],kunyomi:[],meaning:"hợp tác",strokes:8,level:"N2",radical:"十",
 compounds:[{word:"妥協",reading:"だきょう",meaning:"thỏa hiệp"},{word:"協力",reading:"きょうりょく",meaning:"hợp tác"}]},
{char:"譲",onyomi:["ジョウ"],kunyomi:["ゆず-る"],meaning:"nhường",strokes:20,level:"N2",radical:"言"},
{char:"慢",onyomi:["マン"],kunyomi:[],meaning:"chậm, kiêu ngạo",strokes:14,level:"N3",radical:"心",
 compounds:[{word:"我慢",reading:"がまん",meaning:"nhẫn nhịn"}]},
{char:"忍",onyomi:["ニン"],kunyomi:["しの-ぶ"],meaning:"nhẫn nại, chịu đựng",strokes:7,level:"N1",radical:"心",
 compounds:[{word:"忍耐",reading:"にんたい",meaning:"nhẫn nại"}]},
{char:"耐",onyomi:["タイ"],kunyomi:["た-える"],meaning:"chịu đựng",strokes:9,level:"N1",radical:"而",
 compounds:[{word:"忍耐",reading:"にんたい",meaning:"nhẫn nại"}]},
{char:"焦",onyomi:["ショウ"],kunyomi:["あせ-る"],meaning:"sốt ruột, cháy khét",strokes:12,level:"N2",radical:"火",
 compounds:[{word:"焦る",reading:"あせる",meaning:"sốt ruột"}]},
{char:"惑",onyomi:["ワク"],kunyomi:["まど-う"],meaning:"mê hoặc, bối rối",strokes:12,level:"N1",radical:"心",
 compounds:[{word:"戸惑う",reading:"とまどう",meaning:"bối rối"},{word:"迷惑",reading:"めいわく",meaning:"làm phiền"}]},
{char:"励",onyomi:["レイ"],kunyomi:["はげ-む"],meaning:"cố gắng, khích lệ",strokes:7,level:"N2",radical:"力",
 compounds:[{word:"励ます",reading:"はげます",meaning:"động viên"}]},
{char:"慰",onyomi:["イ"],kunyomi:["なぐさ-める"],meaning:"an ủi",strokes:15,level:"N2",radical:"心",
 compounds:[{word:"慰める",reading:"なぐさめる",meaning:"an ủi"}]},
{char:"落",onyomi:["ラク"],kunyomi:["お-ちる"],meaning:"rơi, rụng",strokes:12,level:"N3",radical:"艸",
 compounds:[{word:"見落とす",reading:"みおとす",meaning:"bỏ sót"},{word:"落ちる",reading:"おちる",meaning:"rơi, rớt (thi)"}]},
{char:"組",onyomi:["ソ"],kunyomi:["く-む"],meaning:"tổ chức, ghép",strokes:11,level:"N3",radical:"糸",
 compounds:[{word:"取り組む",reading:"とりくむ",meaning:"bắt tay giải quyết"}]},
{char:"著",onyomi:["チョ"],kunyomi:["いちじる-しい"],meaning:"rõ rệt, trước tác",strokes:11,level:"N1",radical:"艸",
 compounds:[{word:"著しい",reading:"いちじるしい",meaning:"rõ rệt"}]},
{char:"甚",onyomi:["ジン"],kunyomi:["はなは-だ"],meaning:"quá mức",strokes:9,level:"N1",radical:"甘",
 compounds:[{word:"甚だしい",reading:"はなはだしい",meaning:"quá mức"}]},
{char:"覚",onyomi:["カク"],kunyomi:["おぼ-える","さ-める"],meaning:"nhớ, cảm thấy, tỉnh",strokes:12,level:"N3",radical:"見",
 compounds:[{word:"目覚ましい",reading:"めざましい",meaning:"đáng kinh ngạc"},{word:"覚える",reading:"おぼえる",meaning:"nhớ, học thuộc"}]},
{char:"滑",onyomi:["カツ"],kunyomi:["すべ-る"],meaning:"trơn, trượt",strokes:13,level:"N1",radical:"水",
 compounds:[{word:"円滑",reading:"えんかつ",meaning:"suôn sẻ"}]},
{char:"迅",onyomi:["ジン"],kunyomi:[],meaning:"nhanh chóng",strokes:6,level:"N1",radical:"辵",
 compounds:[{word:"迅速",reading:"じんそく",meaning:"nhanh chóng"}]},
{char:"慎",onyomi:["シン"],kunyomi:["つつし-む"],meaning:"thận trọng",strokes:13,level:"N2",radical:"心",
 compounds:[{word:"慎重",reading:"しんちょう",meaning:"thận trọng"}]},
{char:"胆",onyomi:["タン"],kunyomi:[],meaning:"gan dạ, mật",strokes:9,level:"N2",radical:"月",
 compounds:[{word:"大胆",reading:"だいたん",meaning:"táo bạo"}]},
{char:"柔",onyomi:["ジュウ"],kunyomi:["やわ-らかい"],meaning:"mềm dẻo",strokes:9,level:"N2",radical:"木",
 compounds:[{word:"柔軟",reading:"じゅうなん",meaning:"linh hoạt"}]},
{char:"軟",onyomi:["ナン"],kunyomi:["やわ-らかい"],meaning:"mềm",strokes:11,level:"N2",radical:"車",
 compounds:[{word:"柔軟",reading:"じゅうなん",meaning:"linh hoạt"}]},
{char:"促",onyomi:["ソク"],kunyomi:["うなが-す"],meaning:"thúc giục",strokes:9,level:"N1",radical:"人",
 compounds:[{word:"促進",reading:"そくしん",meaning:"thúc đẩy"}]},
{char:"抑",onyomi:["ヨク"],kunyomi:["おさ-える"],meaning:"kìm hãm, ức chế",strokes:7,level:"N1",radical:"手",
 compounds:[{word:"抑制",reading:"よくせい",meaning:"kìm hãm"}]},
{char:"通",onyomi:["ツウ"],kunyomi:["とお-る"],meaning:"thông qua, thông suốt",strokes:10,level:"N3",radical:"辵",
 compounds:[{word:"見通し",reading:"みとおし",meaning:"triển vọng"},{word:"交通",reading:"こうつう",meaning:"giao thông"}]},
{char:"打",onyomi:["ダ"],kunyomi:["う-つ"],meaning:"đánh, đập",strokes:5,level:"N3",radical:"手",
 compounds:[{word:"打開",reading:"だかい",meaning:"tháo gỡ khó khăn"}]},
{char:"極",onyomi:["キョク"],kunyomi:["きわ-める"],meaning:"cực điểm, tận cùng",strokes:12,level:"N2",radical:"木",
 compounds:[{word:"見極める",reading:"みきわめる",meaning:"nhận định rõ ràng"},{word:"積極的",reading:"せっきょくてき",meaning:"tích cực"}]},
];
const KANJI_CLEAN = KANJI.filter(k => k.char !== "time_placeholder");

const GRAMMAR = [
// N5
{level:"N5",pattern:"〜は〜です",meaning:"A là B",structure:"N + は + N/Adj + です",
 usage:"Dùng để giới thiệu, khẳng định một sự vật/sự việc là gì.",
 examples:[{jp:"私は学生です。",vi:"Tôi là học sinh."}]},
{level:"N5",pattern:"〜たいです",meaning:"muốn làm gì",structure:"Vます-stem + たいです",
 usage:"Diễn tả mong muốn của người nói (ngôi thứ nhất).",
 examples:[{jp:"日本へ行きたいです。",vi:"Tôi muốn đi Nhật."}]},
{level:"N5",pattern:"〜てください",meaning:"hãy làm gì (nhờ vả/yêu cầu)",structure:"V-て + ください",
 usage:"Yêu cầu lịch sự người khác làm gì đó.",
 examples:[{jp:"ここに座ってください。",vi:"Hãy ngồi ở đây."}]},
{level:"N5",pattern:"〜ないでください",meaning:"đừng làm gì",structure:"V-ない + でください",
 usage:"Yêu cầu người khác không làm gì đó.",
 examples:[{jp:"写真を撮らないでください。",vi:"Xin đừng chụp ảnh."}]},
{level:"N5",pattern:"〜前に",meaning:"trước khi làm gì",structure:"V (từ điển) / N + の + 前に",
 usage:"Diễn tả hành động xảy ra trước một hành động/thời điểm khác.",
 examples:[{jp:"寝る前に歯を磨きます。",vi:"Tôi đánh răng trước khi ngủ."}]},
{level:"N5",pattern:"〜てから",meaning:"sau khi làm gì",structure:"V-て + から",
 usage:"Diễn tả hành động xảy ra sau khi hoàn thành hành động trước.",
 examples:[{jp:"宿題をしてから、寝ます。",vi:"Sau khi làm bài tập, tôi đi ngủ."}]},
// N4
{level:"N4",pattern:"〜ようになる",meaning:"trở nên có thể/dần dần",structure:"V (thể khả năng/từ điển) + ようになる",
 usage:"Diễn tả sự thay đổi dần dần theo thời gian.",
 examples:[{jp:"日本語が話せるようになりました。",vi:"Tôi đã dần nói được tiếng Nhật."}]},
{level:"N4",pattern:"〜ことがある",meaning:"đã từng làm gì",structure:"V-た + ことがある",
 usage:"Diễn tả kinh nghiệm đã từng trải qua.",
 examples:[{jp:"日本へ行ったことがあります。",vi:"Tôi đã từng đi Nhật."}]},
{level:"N4",pattern:"〜そうです (nghe nói)",meaning:"nghe nói là",structure:"Thể thường + そうです",
 usage:"Truyền đạt lại thông tin nghe được từ người khác.",
 examples:[{jp:"明日は雨が降るそうです。",vi:"Nghe nói ngày mai trời mưa."}]},
{level:"N4",pattern:"〜ば",meaning:"nếu... thì",structure:"Thể điều kiện ば",
 usage:"Diễn tả điều kiện giả định.",
 examples:[{jp:"安ければ買います。",vi:"Nếu rẻ thì tôi mua."}]},
{level:"N4",pattern:"〜てもいいです",meaning:"làm gì cũng được",structure:"V-て + もいいです",
 usage:"Cho phép làm một hành động nào đó.",
 examples:[{jp:"ここに座ってもいいです。",vi:"Ngồi đây cũng được."}]},
{level:"N4",pattern:"〜なければならない",meaning:"phải làm gì",structure:"V-ない (bỏ い) + ければならない",
 usage:"Diễn tả nghĩa vụ, bắt buộc phải làm.",
 examples:[{jp:"薬を飲まなければなりません。",vi:"Phải uống thuốc."}]},
// N3
{level:"N3",pattern:"〜おかげで",meaning:"nhờ có... mà",structure:"N の / V thể thường + おかげで",
 usage:"Diễn tả kết quả tốt nhờ nguyên nhân nào đó.",
 examples:[{jp:"先生のおかげで合格しました。",vi:"Nhờ có thầy mà tôi đã đỗ."}]},
{level:"N3",pattern:"〜せいで",meaning:"tại vì... (nguyên nhân xấu)",structure:"N の / V thể thường + せいで",
 usage:"Diễn tả kết quả xấu do nguyên nhân nào đó.",
 examples:[{jp:"雨のせいで遅れました。",vi:"Tại vì mưa nên tôi bị trễ."}]},
{level:"N3",pattern:"〜わけではない",meaning:"không phải là...",structure:"Thể thường + わけではない",
 usage:"Phủ định một phần, không hoàn toàn phủ định.",
 examples:[{jp:"嫌いなわけではないです。",vi:"Không phải là ghét."}]},
{level:"N3",pattern:"〜たとたん",meaning:"vừa mới... thì",structure:"V-た + とたん",
 usage:"Diễn tả sự việc xảy ra ngay sau hành động khác.",
 examples:[{jp:"家を出たとたん、雨が降ってきた。",vi:"Vừa ra khỏi nhà thì trời đổ mưa."}]},
{level:"N3",pattern:"〜ば〜ほど",meaning:"càng... càng...",structure:"V(ば) + V(từ điển) + ほど",
 usage:"Diễn tả mức độ tăng lên tương ứng.",
 examples:[{jp:"練習すればするほど上手になります。",vi:"Càng luyện tập càng giỏi lên."}]},
{level:"N3",pattern:"〜に違いない",meaning:"chắc chắn là...",structure:"Thể thường + に違いない",
 usage:"Khẳng định mạnh dựa trên suy đoán.",
 examples:[{jp:"彼は忙しいに違いない。",vi:"Chắc chắn anh ấy đang bận."}]},
// N2
{level:"N2",pattern:"〜にもかかわらず",meaning:"mặc dù... nhưng vẫn",structure:"N/Thể thường + にもかかわらず",
 usage:"Diễn tả sự tương phản, ngược với dự đoán.",
 examples:[{jp:"雨にもかかわらず、出かけました。",vi:"Mặc dù trời mưa nhưng tôi vẫn ra ngoài."}]},
{level:"N2",pattern:"〜ものの",meaning:"tuy... nhưng",structure:"Thể thường + ものの",
 usage:"Diễn tả sự tương phản nhẹ giữa hai vế.",
 examples:[{jp:"約束したものの、行けなかった。",vi:"Tuy đã hứa nhưng không đi được."}]},
{level:"N2",pattern:"〜を通じて",meaning:"thông qua...",structure:"N + を通じて",
 usage:"Diễn tả phương tiện hoặc suốt một khoảng thời gian.",
 examples:[{jp:"友達を通じて彼を知りました。",vi:"Tôi biết anh ấy thông qua bạn bè."}]},
{level:"N2",pattern:"〜に伴って",meaning:"đi kèm với, cùng với",structure:"N + に伴って",
 usage:"Diễn tả sự thay đổi song song với một sự việc khác.",
 examples:[{jp:"経済発展に伴って、生活が便利になった。",vi:"Cùng với phát triển kinh tế, cuộc sống tiện lợi hơn."}]},
{level:"N2",pattern:"〜つつある",meaning:"đang dần dần...",structure:"Vます-stem + つつある",
 usage:"Diễn tả một quá trình đang thay đổi dần.",
 examples:[{jp:"環境は改善しつつある。",vi:"Môi trường đang dần được cải thiện."}]},
// N1
{level:"N1",pattern:"〜を余儀なくされる",meaning:"buộc phải...",structure:"N + を余儀なくされる",
 usage:"Diễn tả việc bị ép buộc làm gì do hoàn cảnh.",
 examples:[{jp:"計画の変更を余儀なくされた。",vi:"Buộc phải thay đổi kế hoạch."}]},
{level:"N1",pattern:"〜ずにはいられない",meaning:"không thể không làm...",structure:"V-ない (bỏ ない) + ずにはいられない",
 usage:"Diễn tả cảm xúc/hành động không thể kìm nén.",
 examples:[{jp:"泣かずにはいられなかった。",vi:"Không thể không khóc."}]},
{level:"N1",pattern:"〜が故に",meaning:"chính vì...",structure:"N の / Thể thường + が故に",
 usage:"Diễn tả nguyên nhân trang trọng, văn viết.",
 examples:[{jp:"若さ故に失敗した。",vi:"Chính vì còn trẻ nên đã thất bại."}]},

// ===== Bổ sung thêm ngữ pháp (mở rộng độ phủ N5→N1) =====
// N5 bổ sung
{level:"N5",pattern:"〜てもいいですか",meaning:"tôi có thể... không?",structure:"V-て + もいいですか",
 usage:"Hỏi xin phép làm gì.",examples:[{jp:"入ってもいいですか。",vi:"Tôi vào được không?"}]},
{level:"N5",pattern:"〜ながら",meaning:"vừa... vừa...",structure:"Vます-stem + ながら",
 usage:"Diễn tả hai hành động xảy ra đồng thời.",examples:[{jp:"音楽を聞きながら勉強します。",vi:"Vừa nghe nhạc vừa học."}]},
{level:"N5",pattern:"〜とき",meaning:"khi...",structure:"V/Adj/N + とき",
 usage:"Chỉ thời điểm xảy ra hành động.",examples:[{jp:"暇なとき、映画を見ます。",vi:"Khi rảnh tôi xem phim."}]},
{level:"N5",pattern:"〜から〜まで",meaning:"từ... đến...",structure:"N + から + N + まで",
 usage:"Diễn tả phạm vi thời gian/không gian.",examples:[{jp:"九時から五時まで働きます。",vi:"Tôi làm việc từ 9 giờ đến 5 giờ."}]},
{level:"N5",pattern:"〜が欲しい",meaning:"muốn có...",structure:"N + が欲しい",
 usage:"Diễn tả mong muốn sở hữu vật gì.",examples:[{jp:"新しい靴が欲しいです。",vi:"Tôi muốn có đôi giày mới."}]},
{level:"N5",pattern:"〜と思います",meaning:"tôi nghĩ rằng...",structure:"Thể thường + と思います",
 usage:"Diễn tả ý kiến, suy nghĩ cá nhân.",examples:[{jp:"明日は晴れると思います。",vi:"Tôi nghĩ ngày mai trời sẽ nắng."}]},
{level:"N5",pattern:"〜ことができる",meaning:"có thể làm...",structure:"V(từ điển) + ことができる",
 usage:"Diễn tả khả năng làm gì đó.",examples:[{jp:"漢字を読むことができます。",vi:"Tôi có thể đọc Kanji."}]},
{level:"N5",pattern:"〜でしょう",meaning:"chắc là..., có lẽ...",structure:"Thể thường + でしょう",
 usage:"Diễn tả suy đoán.",examples:[{jp:"明日は雨でしょう。",vi:"Có lẽ ngày mai trời mưa."}]},

// N4 bổ sung
{level:"N4",pattern:"〜てしまう",meaning:"lỡ làm..., làm xong hẳn",structure:"V-て + しまう",
 usage:"Diễn tả sự tiếc nuối hoặc hoàn thành hoàn toàn.",examples:[{jp:"財布を忘れてしまいました。",vi:"Tôi lỡ quên ví."}]},
{level:"N4",pattern:"〜てみる",meaning:"thử làm...",structure:"V-て + みる",
 usage:"Diễn tả việc thử làm gì đó.",examples:[{jp:"日本料理を作ってみます。",vi:"Tôi sẽ thử làm món ăn Nhật."}]},
{level:"N4",pattern:"〜すぎる",meaning:"quá mức...",structure:"V(ます-stem)/Adj-stem + すぎる",
 usage:"Diễn tả mức độ vượt quá bình thường.",examples:[{jp:"食べすぎました。",vi:"Tôi đã ăn quá nhiều."}]},
{level:"N4",pattern:"〜やすい／〜にくい",meaning:"dễ.../khó...",structure:"Vます-stem + やすい／にくい",
 usage:"Diễn tả mức độ dễ hay khó khi làm gì.",examples:[{jp:"この本は読みやすいです。",vi:"Cuốn sách này dễ đọc."}]},
{level:"N4",pattern:"〜たら",meaning:"nếu... thì (giả định)",structure:"V-た + ら",
 usage:"Diễn tả điều kiện giả định, thường dùng trong hội thoại.",examples:[{jp:"雨が降ったら、行きません。",vi:"Nếu trời mưa thì tôi sẽ không đi."}]},
{level:"N4",pattern:"〜と",meaning:"hễ... là...",structure:"V(từ điển)/Adj + と",
 usage:"Diễn tả kết quả tất yếu xảy ra khi điều kiện đúng.",examples:[{jp:"春になると、桜が咲きます。",vi:"Hễ vào xuân là hoa anh đào nở."}]},
{level:"N4",pattern:"〜はずだ",meaning:"chắc hẳn là...",structure:"Thể thường + はずだ",
 usage:"Diễn tả sự chắc chắn dựa trên căn cứ.",examples:[{jp:"彼はもう着いたはずです。",vi:"Anh ấy chắc hẳn đã đến rồi."}]},
{level:"N4",pattern:"〜かもしれない",meaning:"có thể là...",structure:"Thể thường + かもしれない",
 usage:"Diễn tả khả năng, không chắc chắn.",examples:[{jp:"明日雨が降るかもしれません。",vi:"Ngày mai có thể sẽ mưa."}]},
{level:"N4",pattern:"〜させる",meaning:"khiến/bắt ai làm...",structure:"Thể sai khiến (使役形)",
 usage:"Diễn tả sự sai khiến hoặc cho phép ai làm gì.",examples:[{jp:"子供に野菜を食べさせます。",vi:"Tôi bắt con ăn rau."}]},
{level:"N4",pattern:"〜れる／られる (thụ động)",meaning:"bị/được...",structure:"Thể bị động (受身形)",
 usage:"Diễn tả hành động bị/được tác động.",examples:[{jp:"先生に褒められました。",vi:"Tôi được thầy khen."}]},

// N3 bổ sung
{level:"N3",pattern:"〜まま",meaning:"cứ để nguyên như vậy",structure:"V-た/Vない/N の + まま",
 usage:"Diễn tả trạng thái giữ nguyên không thay đổi.",examples:[{jp:"靴を履いたまま入らないでください。",vi:"Đừng mang giày vào."}]},
{level:"N3",pattern:"〜おそれがある",meaning:"có nguy cơ...",structure:"V(từ điển)/N の + おそれがある",
 usage:"Diễn tả khả năng xảy ra điều không tốt.",examples:[{jp:"台風が来るおそれがあります。",vi:"Có nguy cơ bão sẽ đến."}]},
{level:"N3",pattern:"〜からいうと／からいえば",meaning:"xét từ góc độ...",structure:"N + からいうと",
 usage:"Diễn tả quan điểm đánh giá từ góc độ nào đó.",examples:[{jp:"経験からいうと、練習が一番大切です。",vi:"Xét từ kinh nghiệm, luyện tập là quan trọng nhất."}]},
{level:"N3",pattern:"〜恐れず",meaning:"không sợ...",structure:"N/V(từ điển)を + 恐れず",
 usage:"Diễn tả hành động dù không sợ điều gì đó.",examples:[{jp:"失敗を恐れずに挑戦しよう。",vi:"Đừng sợ thất bại mà hãy thử thách."}]},
{level:"N3",pattern:"〜において",meaning:"trong, tại (trang trọng)",structure:"N + において",
 usage:"Chỉ địa điểm, lĩnh vực, thời điểm một cách trang trọng.",examples:[{jp:"この分野において彼は専門家です。",vi:"Trong lĩnh vực này anh ấy là chuyên gia."}]},
{level:"N3",pattern:"〜において",meaning:"về mặt, trong (lĩnh vực)",structure:"N + における",
 usage:"Dạng bổ nghĩa danh từ của において.",examples:[{jp:"日本における経済成長。",vi:"Sự tăng trưởng kinh tế ở Nhật Bản."}]},
{level:"N3",pattern:"〜반드시〜わけがない",meaning:"không đời nào...",structure:"Thể thường + わけがない",
 usage:"Phủ định mạnh, khẳng định điều đó không thể xảy ra.",examples:[{jp:"彼が嘘をつくわけがない。",vi:"Anh ấy không đời nào nói dối."}]},
{level:"N3",pattern:"〜てはじめて",meaning:"chỉ sau khi... mới...",structure:"V-て + はじめて",
 usage:"Diễn tả điều chỉ nhận ra/xảy ra sau khi trải qua việc gì.",examples:[{jp:"社会人になってはじめて親のありがたさが分かった。",vi:"Chỉ sau khi đi làm tôi mới hiểu công ơn cha mẹ."}]},

// N2 bổ sung
{level:"N2",pattern:"〜あげく",meaning:"cuối cùng thì... (kết quả xấu)",structure:"V-た / N の + あげく",
 usage:"Diễn tả kết quả không tốt sau một quá trình dài.",examples:[{jp:"さんざん悩んだあげく、諦めた。",vi:"Sau khi lo lắng rất nhiều, cuối cùng tôi đã từ bỏ."}]},
{level:"N2",pattern:"〜きっかけに",meaning:"nhân dịp, lấy đó làm cơ hội",structure:"N/V(た) + きっかけに",
 usage:"Diễn tả một sự việc trở thành cơ hội cho việc khác.",examples:[{jp:"留学をきっかけに人生が変わった。",vi:"Nhân dịp du học mà cuộc sống tôi đã thay đổi."}]},
{level:"N2",pattern:"〜limit以上",meaning:"đã... thì...",structure:"Thể thường + 以上",
 usage:"Diễn tả điều kiện tất yếu do hoàn cảnh đã xác định.",examples:[{jp:"約束した以上、守らなければならない。",vi:"Đã hứa rồi thì phải giữ lời."}]},
{level:"N2",pattern:"〜反面",meaning:"mặt khác thì...",structure:"Thể thường + 反面",
 usage:"Diễn tả hai mặt trái ngược của cùng một sự việc.",examples:[{jp:"便利な反面、危険もある。",vi:"Tiện lợi nhưng mặt khác cũng có nguy hiểm."}]},
{level:"N2",pattern:"〜末に",meaning:"sau cùng, rốt cuộc",structure:"V-た / N の + 末に",
 usage:"Diễn tả kết quả sau một quá trình dài, vất vả.",examples:[{jp:"長い議論の末に結論が出た。",vi:"Sau cuộc tranh luận dài, kết luận đã được đưa ra."}]},
{level:"N2",pattern:"〜たびに",meaning:"mỗi lần...",structure:"V(từ điển) / N の + たびに",
 usage:"Diễn tả điều lặp lại mỗi khi một việc xảy ra.",examples:[{jp:"彼女に会うたびに元気をもらう。",vi:"Mỗi lần gặp cô ấy tôi lại thấy vui vẻ."}]},

// N1 bổ sung
{level:"N1",pattern:"〜にたえない",meaning:"không chịu nổi, không đáng...",structure:"N + にたえない",
 usage:"Diễn tả cảm xúc mạnh không kìm được, hoặc không xứng đáng.",examples:[{jp:"見るにたえない光景だった。",vi:"Đó là cảnh tượng không thể chịu nổi khi nhìn."}]},
{level:"N1",pattern:"〜ばこそ",meaning:"chính vì... mới...",structure:"V-ば + こそ",
 usage:"Nhấn mạnh nguyên nhân duy nhất, thường dùng văn trang trọng.",examples:[{jp:"愛すればこそ、厳しく言うのです。",vi:"Chính vì yêu thương mới nói nghiêm khắc."}]},
{level:"N1",pattern:"〜きらいがある",meaning:"có xu hướng (không tốt)...",structure:"V(từ điển)/N の + きらいがある",
 usage:"Diễn tả khuynh hướng tiêu cực cố hữu.",examples:[{jp:"彼は物事を悲観的に考えるきらいがある。",vi:"Anh ấy có xu hướng suy nghĩ bi quan."}]},
{level:"N1",pattern:"〜んばかりに",meaning:"gần như là, suýt nữa thì",structure:"V-ない (bỏ ない) + んばかりに",
 usage:"Diễn tả trạng thái gần như xảy ra nhưng chưa hẳn.",examples:[{jp:"泣かんばかりに喜んだ。",vi:"Vui đến mức gần như bật khóc."}]},
{level:"N1",pattern:"〜てやまない",meaning:"mãi mãi..., không ngừng...",structure:"V-て + やまない",
 usage:"Diễn tả cảm xúc/mong muốn liên tục, sâu sắc, văn trang trọng.",examples:[{jp:"皆様のご健康を願ってやみません。",vi:"Tôi mãi mong mọi người luôn khỏe mạnh."}]},
{level:"N1",pattern:"〜ずくめ",meaning:"toàn là..., đầy...",structure:"N + ずくめ",
 usage:"Diễn tả trạng thái toàn bộ đều là một thứ gì đó.",examples:[{jp:"今年はいいことずくめだった。",vi:"Năm nay toàn là chuyện tốt."}]},
];

const READINGS = [
{level:"N5",title:"私の一日",
 text:"私は毎朝六時に起きます。顔を洗って、朝ごはんを食べます。それから学校へ行きます。学校で友達と勉強します。授業は九時から始まります。昼に友達とお弁当を食べます。夕方、家に帰って宿題をします。夜十時に寝ます。",
 vocab:["起きる","顔","洗う","朝ごはん","学校","友達","勉強","授業","弁当","宿題","寝る"]},
{level:"N4",title:"日本語を勉強する理由",
 text:"私が日本語を勉強し始めたのは三年前です。最初はアニメが好きだったからですが、勉強するうちに日本の文化にも興味を持つようになりました。漢字は難しいですが、毎日少しずつ覚えるようにしています。将来、日本で働きたいと思っています。",
 vocab:["理由","最初","文化","興味","漢字","難しい","覚える","将来","働く"]},
{level:"N3",title:"環境問題について",
 text:"最近、環境問題がますます深刻になっています。地球温暖化の影響で、異常気象が増えているそうです。私たちにできることは小さいかもしれませんが、一人一人が努力すれば、環境は少しずつ改善されるはずです。例えば、ゴミを減らしたり、公共交通機関を利用したりすることが大切です。",
 vocab:["環境問題","深刻","地球温暖化","影響","異常気象","努力","改善","公共交通機関"]},
{level:"N2",title:"働き方の変化",
 text:"近年、働き方に関する価値観は大きく変わりつつある。かつては終身雇用が当たり前とされていたが、現在では転職を経験する人も少なくない。また、テレワークの普及にもかかわらず、依然として対面での仕事を重視する企業も存在する。今後、企業と労働者の双方にとって望ましい働き方が模索されていくだろう。",
 vocab:["価値観","終身雇用","転職","普及","依然として","重視","模索"]},
];
